version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    groups:
      dependencias-seguras:
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /back
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /front
    schedule:
      interval: monthly
