import { definirLeccionWeb, paso } from "./definirLeccion";

export const alertasPriorizar = definirLeccionWeb({
  id: "alertas-priorizar",
  pantalla: "alertas",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR", "ALMACENISTA", "COBRADOR"],
  titulo: ["Convertir alertas en acciones", "Turn alerts into actions"],
  objetivo: [
    "Revisar las categorías con pendientes y abrir el módulo donde se resuelve cada una.",
    "Review categories with pending work and open the module where each issue is resolved.",
  ],
  resultado: [
    "Resuelves inventario, cartera, pedidos o rutas desde el aviso.",
    "You resolve stock, portfolio, orders, or routes from the alert.",
  ],
  responsable: ["Todos los roles", "All roles"],
  rutaReal: "/alertas",
  guion: [
    paso(
      "alertas-revisar",
      "Identifica el grupo de trabajo",
      "Alertas empresariales → grupos",
      "La pantalla agrupa inventario bajo, clientes vencidos, pedidos atrasados y rutas incompletas; no tiene filtros.",
      "Ejemplo: Almacén atiende Inventario bajo; Cobranza prioriza Clientes vencidos.",
      "Revisa los grupos visibles para tu rol.",
      "Los grupos de alertas están visibles.",
      "alertas.grupos",
      "lectura",
    ),
    paso(
      "alertas-actualizar",
      "Actualiza la información",
      "Alertas empresariales → Actualizar",
      "Actualiza después de resolver un problema en su módulo.",
      "Ejemplo: tras surtir un producto, pulsa Actualizar para comprobar si deja de estar bajo.",
      "Pulsa Actualizar.",
      "La consulta de alertas vuelve a ejecutarse.",
      "alertas.actualizar",
      "click",
    ),
    paso(
      "alertas-comprobar-actualizacion",
      "Comprueba la hora de actualización",
      "Alertas empresariales → estado de actualización",
      "Antes de abrir un módulo, confirma que estás leyendo el resultado recién consultado.",
      "Ejemplo: si actualizaste después de surtir, la hora debe corresponder a esa revisión.",
      "Revisa la hora de la última actualización.",
      "El estado de actualización está visible.",
      "alertas.estado-actualizacion",
      "lectura",
    ),
    paso(
      "alertas-abrir",
      "Abre el módulo cuando exista enlace",
      "Alerta → Abrir módulo",
      "No todas las filas son enlaces; usa Abrir módulo únicamente cuando la pantalla lo ofrezca.",
      "Ejemplo: un cliente vencido puede abrir su expediente.",
      "Pulsa Abrir módulo en una alerta accionable.",
      "La práctica conserva contexto al navegar al módulo.",
      "alertas.abrir-modulo",
      "click",
    ),
  ],
});
