import { definirLeccionWeb, paso } from "./definirLeccion";

export const clientesEdicion = definirLeccionWeb({
  id: "clientes-edicion",
  pantalla: "clientes",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR"],
  titulo: ["Actualizar datos del cliente", "Update customer information"],
  objetivo: [
    "Editar contacto y localidad conservando trazabilidad.",
    "Edit contact and locality while preserving traceability.",
  ],
  resultado: [
    "El expediente queda actual y listo para ruta o venta.",
    "The record is current and ready for a route or sale.",
  ],
  responsable: [
    "Administración · Contabilidad · Ventas",
    "Administration · Accounting · Sales",
  ],
  rutaReal: "/clientes",
  guion: [
    paso(
      "buscar-cliente-editar",
      "Encuentra al cliente",
      "Clientes → buscador",
      "Busca con un dato verificable antes de editar.",
      "Ejemplo: teléfono 2225550147.",
      "Escribe el dato de búsqueda.",
      "El buscador contiene un valor.",
      "clientes.busqueda.campo",
      "input",
    ),
    paso(
      "buscar-cliente-editar-boton",
      "Consulta la coincidencia",
      "Clientes → Buscar",
      "Verifica el dato capturado.",
      "Ejemplo: diez dígitos completos, sin cambiar el último número.",
      "Pulsa Buscar.",
      "La lista muestra las coincidencias.",
      "clientes.busqueda.ejecutar",
      "click",
    ),
    paso(
      "abrir-edicion",
      "Abre Editar",
      "Clientes → fila correcta → Editar",
      "Confirma nombre y localidad antes de abrir el formulario.",
      "Ejemplo: edita Ana López · Centro, no otra Ana López.",
      "Pulsa Editar en la fila correcta.",
      "Se abre el formulario real Editar cliente.",
      "clientes.edicion.abrir",
      "click",
    ),
    paso(
      "editar-telefono",
      "Actualiza el teléfono",
      "Editar cliente → Teléfono",
      "Captura únicamente el nuevo teléfono confirmado.",
      "Ejemplo: 2225550199; no inventes números faltantes.",
      "Escribe el teléfono nuevo.",
      "El campo contiene un teléfono válido.",
      "clientes.edicion.telefono",
      "input",
    ),
    paso(
      "editar-localidad",
      "Selecciona la localidad",
      "Editar cliente → Localidad",
      "La localidad debe existir en el catálogo.",
      "Ejemplo: San Miguel, Puebla; no escribas una colonia libre.",
      "Selecciona la localidad correcta.",
      "El selector conserva una localidad.",
      "clientes.edicion.localidad",
      "select",
    ),
    paso(
      "editar-direccion",
      "Actualiza la dirección",
      "Editar cliente → Dirección",
      "Incluye calle, número y referencia útil.",
      "Ejemplo: Av. Reforma 120, frente al mercado.",
      "Escribe la dirección verificada.",
      "La dirección no está vacía y es válida.",
      "clientes.edicion.direccion",
      "input",
    ),
    paso(
      "guardar-edicion",
      "Guarda los cambios",
      "Editar cliente → Guardar cambios",
      "Relee teléfono, localidad y dirección antes de guardar.",
      "Ejemplo: 2225550199 · San Miguel · Av. Reforma 120.",
      "Pulsa Guardar cambios.",
      "La edición queda registrada sólo en este navegador.",
      "clientes.edicion.guardar",
      "mutacion-local",
      { metodo: "PATCH", ruta: "/clientes/:id" },
    ),
  ],
});
