import { definirLeccionWeb, paso } from "./definirLeccion";

export const clientesExpediente = definirLeccionWeb({
  id: "clientes-expediente",
  pantalla: "clientes",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR", "COBRADOR"],
  titulo: ["Encontrar y entender un cliente", "Find and understand a customer"],
  objetivo: [
    "Buscar por nombre, teléfono, dirección o tarjeta y leer su expediente.",
    "Search by name, phone, address, or card and read the customer record.",
  ],
  resultado: [
    "Confirmas identidad, saldo, atrasos y pedidos antes de actuar.",
    "You confirm identity, balance, arrears, and orders before acting.",
  ],
  responsable: [
    "Administración · Contabilidad · Ventas · Cobranza",
    "Administration · Accounting · Sales · Collections",
  ],
  rutaReal: "/clientes",
  guion: [
    paso(
      "buscar-dato",
      "Escribe un dato que sí conozcas",
      "Clientes → buscador principal",
      "Usa un solo dato confiable: teléfono, tarjeta, nombre, dirección o localidad.",
      "Ejemplo: 2225550147. No mezcles un teléfono con el nombre de otra persona.",
      "Escribe el dato de búsqueda.",
      "El buscador contiene un valor.",
      "clientes.busqueda.campo",
      "input",
    ),
    paso(
      "ejecutar-busqueda",
      "Ejecuta la búsqueda",
      "Clientes → botón Buscar",
      "Revisa el texto una vez antes de consultar.",
      "Ejemplo: si capturaste 2225550147, verifica los diez dígitos antes de pulsar Buscar.",
      "Pulsa Buscar una sola vez.",
      "La lista se actualiza con las coincidencias.",
      "clientes.busqueda.ejecutar",
      "click",
    ),
    paso(
      "abrir-expediente",
      "Abre el expediente correcto",
      "Clientes → resultado → Ver expediente",
      "Compara nombre, teléfono, dirección y localidad; no elijas sólo por nombre.",
      "Ejemplo: Ana López de Centro no es Ana López de San Miguel.",
      "Abre Ver expediente en la coincidencia correcta.",
      "La práctica continúa dentro del expediente elegido.",
      "clientes.expediente.abrir",
      "click",
    ),
    paso(
      "leer-identidad",
      "Confirma la identidad",
      "Expediente → Datos del cliente",
      "Confirma al menos dos datos antes de cobrar o editar.",
      "Ejemplo: teléfono + localidad, o dirección + número de tarjeta.",
      "Revisa los datos generales del expediente.",
      "El bloque de identidad está visible.",
      "clientes.expediente.datos",
      "lectura",
    ),
    paso(
      "leer-saldo",
      "Revisa saldo y pendientes",
      "Expediente → indicadores de saldo",
      "Separa saldo actual, vencido y total abonado.",
      "Ejemplo: saldo actual $800 y vencido $200 significa que no todo el saldo está atrasado.",
      "Revisa Saldo actual, Saldo vencido y próximos movimientos.",
      "Los indicadores financieros del expediente están visibles.",
      "clientes.expediente.resumen",
      "lectura",
    ),
  ],
});
