import { definirLeccionWeb, paso } from "./definirLeccion";

export const clientesAlta = definirLeccionWeb({
  id: "clientes-alta",
  pantalla: "clientes",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR"],
  titulo: ["Crear el expediente del cliente", "Create a customer record"],
  objetivo: [
    "Registrar una sola vez identidad, contacto, dirección y localidad.",
    "Record identity, contact, address, and location once.",
  ],
  resultado: [
    "Cliente localizable y listo para venta, pedido, saldo o ruta.",
    "Searchable customer ready for sale, order, balance, or route.",
  ],
  responsable: [
    "Administración · Contabilidad · Ventas",
    "Administration · Accounting · Sales",
  ],
  rutaReal: "/clientes",
  guion: [
    paso(
      "alta-comprobar",
      "Comprueba que no exista",
      "Clientes → buscador",
      "Busca teléfono o dirección antes de crear otro expediente.",
      "Ejemplo: busca 2225550123 antes de registrar a Rosa.",
      "Escribe el dato que usarás para descartar duplicados.",
      "El dato está capturado.",
      "clientes.busqueda.campo",
      "input",
    ),
    paso(
      "alta-buscar",
      "Revisa coincidencias",
      "Clientes → Buscar",
      "Un expediente duplicado divide saldo e historial.",
      "Ejemplo: si aparece el mismo teléfono, abre ese registro en vez de crear otro.",
      "Pulsa Buscar y revisa la lista.",
      "La consulta termina.",
      "clientes.busqueda.ejecutar",
      "click",
    ),
    paso(
      "alta-abrir",
      "Abre Nuevo cliente",
      "Clientes → Nuevo",
      "Hazlo sólo si las coincidencias no corresponden a la persona.",
      "Ejemplo: mismo apellido con teléfono distinto no basta; compara dirección.",
      "Pulsa Nuevo.",
      "Se abre el formulario Nuevo cliente.",
      "clientes.alta.abrir",
      "click",
    ),
    paso(
      "alta-nombre",
      "Captura el nombre",
      "Nuevo cliente → Nombre completo",
      "Escribe el nombre como fue confirmado por la persona.",
      "Ejemplo: Rosa Martínez López.",
      "Captura el nombre completo.",
      "El nombre cumple la longitud requerida.",
      "clientes.alta.nombre",
      "input",
    ),
    paso(
      "alta-telefono",
      "Captura el teléfono",
      "Nuevo cliente → Teléfono",
      "Usa el número confirmado, no uno de referencia sin aclararlo.",
      "Ejemplo: 2225550123.",
      "Captura el teléfono.",
      "El teléfono cumple el formato permitido.",
      "clientes.alta.telefono",
      "input",
    ),
    paso(
      "alta-filtrar-localidad",
      "Busca la localidad",
      "Nuevo cliente → filtro de localidad",
      "Filtra por nombre o estado para reducir errores.",
      "Ejemplo: escribe San Miguel o Puebla.",
      "Escribe el filtro de localidad.",
      "El filtro contiene un valor.",
      "clientes.alta.localidad-buscar",
      "input",
    ),
    paso(
      "alta-localidad",
      "Elige la localidad",
      "Nuevo cliente → Localidad",
      "Selecciona sólo una localidad ya registrada.",
      "Ejemplo: San Miguel · Puebla.",
      "Selecciona la localidad correcta.",
      "El formulario conserva una localidad.",
      "clientes.alta.localidad",
      "select",
    ),
    paso(
      "alta-direccion",
      "Captura la dirección",
      "Nuevo cliente → Dirección",
      "Incluye datos suficientes para venta y cobranza.",
      "Ejemplo: Calle 5 de Mayo 24, casa azul.",
      "Escribe la dirección completa.",
      "La dirección es válida.",
      "clientes.alta.direccion",
      "input",
    ),
    paso(
      "alta-guardar",
      "Crea el expediente",
      "Nuevo cliente → Guardar",
      "Revisa nombre, teléfono, localidad y dirección; el saldo debe iniciar sin inventarse.",
      "Ejemplo: Rosa Martínez · 2225550123 · San Miguel.",
      "Pulsa Guardar.",
      "El alta queda simulada sólo en este navegador.",
      "clientes.alta.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/clientes" },
    ),
  ],
});
