import { definirLeccionWeb, paso } from "./definirLeccion";

export const cobranzaAbono = definirLeccionWeb({
  id: "cobranza-abono",
  pantalla: "clientes",
  roles: ["ADMINISTRADOR", "CONTABLE", "COBRADOR"],
  titulo: ["Registrar un abono", "Record a payment"],
  objetivo: [
    "Aplicar el pago correcto y dejar evidencia del método.",
    "Apply the correct payment and record its method.",
  ],
  resultado: [
    "Baja el saldo, queda historial y entra al corte del operador.",
    "Balance decreases, history is stored, and the payment enters the operator closing.",
  ],
  responsable: [
    "Administración · Contabilidad · Cobranza",
    "Administration · Accounting · Collections",
  ],
  tipoSimulador: "ABONO",
  rutaReal: "/clientes",
  guion: [
    paso(
      "abono-abrir",
      "Abre Registrar abono",
      "Clientes → Registrar abono",
      "Este flujo reduce un saldo existente; no crea una venta.",
      "Ejemplo: la clienta entrega $250 de una deuda vigente.",
      "Pulsa Registrar abono.",
      "Se abre el formulario Registrar abono.",
      "clientes.abono.abrir",
      "click",
    ),
    paso(
      "abono-buscar",
      "Busca al cliente",
      "Registrar abono → Cliente",
      "Busca con teléfono o tarjeta cuando haya nombres parecidos.",
      "Ejemplo: tarjeta NX-2048.",
      "Escribe el dato de búsqueda.",
      "El buscador contiene un valor.",
      "clientes.abono.cliente.buscar",
      "input",
    ),
    paso(
      "abono-elegir",
      "Selecciona el expediente",
      "Cliente → resultados",
      "Compara saldo, teléfono y localidad antes de aplicar dinero.",
      "Ejemplo: Ana López · saldo $900 · Centro.",
      "Pulsa la coincidencia correcta con saldo pendiente.",
      "El cliente y su saldo aparecen en el formulario.",
      "clientes.abono.cliente.opcion",
      "click",
    ),
    paso(
      "abono-monto",
      "Captura el monto recibido",
      "Registrar abono → Monto recibido",
      "Escribe exactamente el dinero comprobado.",
      "Ejemplo: $250; no uses Liquidar si sólo entregó una parte.",
      "Escribe el monto.",
      "El monto es mayor a cero y no supera el saldo permitido.",
      "clientes.abono.monto",
      "input",
    ),
    paso(
      "abono-metodo",
      "Elige el método",
      "Registrar abono → Método",
      "El método debe coincidir con la evidencia del pago.",
      "Ejemplo: Transferencia si existe comprobante bancario.",
      "Selecciona el método recibido.",
      "El selector conserva el método.",
      "clientes.abono.metodo",
      "select",
    ),
    paso(
      "abono-guardar",
      "Registra el abono",
      "Registrar abono → Registrar abono",
      "Revisa cliente, saldo anterior, monto y método antes de confirmar.",
      "Ejemplo: saldo $900 − abono $250 = saldo $650.",
      "Pulsa Registrar abono.",
      "El resultado Antes/Ahora aparece sólo en este navegador.",
      "clientes.abono.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/abonos" },
    ),
  ],
});
