import { definirLeccionWeb, paso } from "./definirLeccion";

export const comprasProveedores = definirLeccionWeb({
  id: "compras-proveedores",
  pantalla: "compras",
  roles: ["ADMINISTRADOR", "ALMACENISTA"],
  titulo: ["Crear el catálogo de proveedores", "Create the supplier catalog"],
  objetivo: [
    "Registrar el proveedor y sus datos de contacto antes de usarlo en compras o pedidos.",
    "Register a supplier and its contact details before using it in purchases or orders.",
  ],
  resultado: [
    "Proveedor activo con contacto, datos fiscales y trazabilidad.",
    "Active supplier with contact, tax data, and traceability.",
  ],
  responsable: ["Administración · Almacén", "Administration · Warehouse"],
  rutaReal: "/compras",
  guion: [
    paso(
      "proveedor-abrir",
      "Abre Nuevo proveedor",
      "Compras y proveedores → Proveedor",
      "Este botón crea el proveedor; la pestaña Proveedores sólo consulta los existentes.",
      "Ejemplo: Textiles del Centro, no el nombre de una persona que compra.",
      "Pulsa Proveedor.",
      "Se abre Nuevo proveedor.",
      "compras.proveedor.abrir-nuevo",
      "click",
    ),
    paso(
      "proveedor-nombre",
      "Captura el nombre",
      "Nuevo proveedor → Nombre",
      "Usa la razón comercial confirmada.",
      "Ejemplo: Textiles del Centro.",
      "Escribe el nombre.",
      "El nombre es válido.",
      "compras.proveedor.nombre",
      "input",
    ),
    paso(
      "proveedor-contacto",
      "Captura el contacto",
      "Nuevo proveedor → Contacto",
      "Escribe a la persona que atiende pedidos.",
      "Ejemplo: Laura Pérez.",
      "Escribe el contacto.",
      "El contacto queda capturado.",
      "compras.proveedor.contacto",
      "input",
    ),
    paso(
      "proveedor-telefono",
      "Captura el teléfono",
      "Nuevo proveedor → Teléfono",
      "Usa el número confirmado por el proveedor.",
      "Ejemplo: 2225550188.",
      "Escribe el teléfono.",
      "El teléfono tiene un formato válido.",
      "compras.proveedor.telefono",
      "input",
    ),
    paso(
      "proveedor-correo",
      "Captura el correo",
      "Nuevo proveedor → Correo",
      "Usa una cuenta que reciba órdenes o facturas.",
      "Ejemplo: pedidos@textilescentro.mx.",
      "Escribe el correo.",
      "El correo es válido.",
      "compras.proveedor.correo",
      "input",
    ),
    paso(
      "proveedor-rfc",
      "Captura el RFC",
      "Nuevo proveedor → RFC",
      "Copia el RFC del documento fiscal, sin inventarlo.",
      "Ejemplo: TCE010203AB4.",
      "Escribe el RFC.",
      "El RFC queda capturado.",
      "compras.proveedor.rfc",
      "input",
    ),
    paso(
      "proveedor-guardar",
      "Guarda el proveedor",
      "Nuevo proveedor → Guardar",
      "Revisa nombre, contacto y medios de comunicación.",
      "Ejemplo final: Textiles del Centro · Laura Pérez · pedidos@textilescentro.mx.",
      "Pulsa Guardar.",
      "El proveedor queda simulado sólo en este navegador.",
      "compras.proveedor.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/proveedores" },
    ),
  ],
});
