import { definirLeccionWeb, paso } from "./definirLeccion";

export const comprasProveedor = definirLeccionWeb({
  id: "compras-proveedor",
  pantalla: "compras",
  roles: ["ADMINISTRADOR", "ALMACENISTA"],
  titulo: ["Registrar compra y entrada", "Record a purchase and stock receipt"],
  objetivo: [
    "Registrar una entrada con proveedor, fecha, producto, cantidad y costo.",
    "Record a stock receipt with supplier, date, product, quantity, and cost.",
  ],
  resultado: [
    "Compra con folio generado y movimiento de inventario ligado al proveedor.",
    "Purchase with a generated receipt and a stock movement linked to the supplier.",
  ],
  responsable: ["Administración · Almacén", "Administration · Warehouse"],
  rutaReal: "/compras",
  guion: [
    paso(
      "compra-abrir",
      "Abre Registrar compra",
      "Compras y proveedores → Compra",
      "Usa Compra para una entrada de inventario; Proveedor sólo crea el catálogo.",
      "Ejemplo: llegó una factura con 5 colchas.",
      "Pulsa Compra.",
      "Se abre Registrar compra.",
      "compras.compra.abrir-nueva",
      "click",
    ),
    paso(
      "compra-proveedor",
      "Selecciona el proveedor",
      "Registrar compra → Proveedor",
      "Elige quien realmente surtió la mercancía.",
      "Ejemplo: Textiles del Centro.",
      "Selecciona el proveedor.",
      "El formulario conserva un proveedor.",
      "compras.compra.proveedor",
      "select",
    ),
    paso(
      "compra-fecha",
      "Captura la fecha",
      "Registrar compra → Fecha de compra",
      "Usa la fecha del documento o recepción comprobada.",
      "Ejemplo: 25/08/2026.",
      "Selecciona la fecha.",
      "La fecha queda capturada.",
      "compras.compra.fecha",
      "input",
    ),
    paso(
      "compra-continuar-mercancia",
      "Continúa a mercancía",
      "Entrada de mercancía → Continuar",
      "Proveedor y fecha deben quedar comprobados antes del conteo.",
      "Ejemplo: Textiles del Centro · 25/08/2026.",
      "Pulsa Continuar.",
      "Se abre el paso de mercancía.",
      "compras.compra.continuar-1",
      "click",
    ),
    paso(
      "compra-buscar-producto",
      "Busca el producto",
      "Registrar compra → Producto registrado",
      "No escribas un artículo libre si ya existe en Inventario.",
      "Ejemplo: SKU COL-MAT-01.",
      "Escribe producto, marca, SKU o código.",
      "El buscador contiene un valor.",
      "compras.compra.producto.buscar",
      "input",
    ),
    paso(
      "compra-elegir-producto",
      "Selecciona el producto",
      "Producto registrado → resultados",
      "Compara nombre y SKU.",
      "Ejemplo: Colcha matrimonial · COL-MAT-01.",
      "Pulsa el producto correcto.",
      "El producto queda seleccionado.",
      "compras.compra.producto.opcion",
      "click",
    ),
    paso(
      "compra-cantidad",
      "Captura la cantidad",
      "Registrar compra → Cantidad",
      "Cuenta físicamente las piezas recibidas.",
      "Ejemplo: 5 piezas.",
      "Escribe la cantidad.",
      "La cantidad es un entero mayor a cero.",
      "compras.compra.cantidad",
      "input",
    ),
    paso(
      "compra-costo",
      "Captura el costo unitario",
      "Registrar compra → Costo unitario",
      "Usa el costo por pieza, no el total de factura.",
      "Ejemplo: $650 por unidad.",
      "Escribe el costo unitario.",
      "El costo es válido.",
      "compras.compra.costo",
      "input",
    ),
    paso(
      "compra-continuar-revision",
      "Revisa la entrada",
      "Entrada de mercancía → Continuar",
      "Antes de afectar inventario revisa piezas, costo y existencia resultante.",
      "Ejemplo: existencia 3 → 8.",
      "Pulsa Continuar.",
      "Se abre la revisión final.",
      "compras.compra.continuar-2",
      "click",
    ),
    paso(
      "compra-guardar",
      "Registra la entrada",
      "Registrar compra → Registrar entrada",
      "Revisa proveedor, fecha, producto, cantidad y costo.",
      "Ejemplo: Textiles del Centro · 5 × $650.",
      "Pulsa Registrar entrada.",
      "La compra queda simulada sólo en este navegador.",
      "compras.compra.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/compras" },
    ),
  ],
});
