import { definirLeccionWeb, paso } from "./definirLeccion";

export const configuracionLocalidades = definirLeccionWeb({
  id: "configuracion-localidades",
  pantalla: "configuracion",
  roles: ["ADMINISTRADOR"],
  titulo: [
    "Crear localidades antes que clientes",
    "Create locations before customers",
  ],
  objetivo: [
    "Preparar el catálogo geográfico que usarán clientes y rutas.",
    "Prepare the geographic catalog used by customers and routes.",
  ],
  resultado: [
    "Localidades activas y buscables por nombre o estado.",
    "Active locations searchable by name or state.",
  ],
  responsable: ["Administración", "Administration"],
  rutaReal: "/configuracion",
  guion: [
    paso(
      "localidades-abrir-tab",
      "Entra al catálogo correcto",
      "Configuración → Localidades",
      "No uses Importar Excel ni Auditoría para un alta individual.",
      "Ejemplo: una zona nueva se registra en Localidades.",
      "Pulsa Localidades.",
      "La lista de localidades está visible.",
      "configuracion.localidades.tab",
      "click",
    ),
    paso(
      "localidades-nueva",
      "Abre Nueva localidad",
      "Localidades → Localidad",
      "Antes verifica visualmente que el nombre no esté repetido.",
      "Ejemplo: San Miguel · Puebla.",
      "Pulsa Localidad.",
      "Se abre el formulario Nueva localidad.",
      "configuracion.localidades.nueva",
      "click",
    ),
    paso(
      "localidades-nombre",
      "Escribe el nombre",
      "Nueva localidad → Nombre",
      "Usa el nombre reconocido por el negocio.",
      "Ejemplo: San Miguel.",
      "Captura el nombre de la localidad.",
      "El nombre cumple la longitud requerida.",
      "configuracion.localidades.nombre",
      "input",
    ),
    paso(
      "localidades-estado",
      "Escribe el estado",
      "Nueva localidad → Estado",
      "El estado distingue localidades con nombres iguales.",
      "Ejemplo: Puebla.",
      "Captura el estado.",
      "El estado cumple la longitud requerida.",
      "configuracion.localidades.estado",
      "input",
    ),
    paso(
      "localidades-guardar",
      "Guarda la localidad",
      "Nueva localidad → Guardar",
      "Revisa nombre y estado; las localidades nuevas quedan activas automáticamente.",
      "Ejemplo final: San Miguel · Puebla.",
      "Pulsa Guardar.",
      "La localidad queda simulada sólo en este navegador.",
      "configuracion.localidades.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/localidades" },
    ),
  ],
});
