import { definirLeccionWeb, paso } from "./definirLeccion";

export const configuracionOperacion = definirLeccionWeb({
  id: "configuracion-operacion",
  pantalla: "configuracion",
  roles: ["ADMINISTRADOR"],
  titulo: [
    "Revisar catálogos y auditoría",
    "Review catalogs and audit history",
  ],
  objetivo: [
    "Comprobar qué cambió, quién lo hizo y qué dato había antes.",
    "Verify what changed, who changed it, and the previous value.",
  ],
  resultado: [
    "Catálogos activos revisados y cambios importantes trazables.",
    "Active catalogs reviewed and important changes traceable.",
  ],
  responsable: ["Administración", "Administration"],
  rutaReal: "/configuracion",
  guion: [
    paso(
      "operacion-localidades",
      "Revisa Localidades",
      "Configuración → Localidades",
      "Clientes y rutas sólo pueden usar localidades registradas.",
      "Ejemplo: una localidad dada de baja no aparece en nuevas selecciones.",
      "Pulsa Localidades.",
      "El catálogo está visible.",
      "configuracion.localidades.tab",
      "click",
    ),
    paso(
      "operacion-listado",
      "Distingue estado del catálogo",
      "Localidades → listado",
      "Revisa nombre, estado y si ofrece Baja o Reactivar.",
      "Ejemplo: una fila con Reactivar está inactiva.",
      "Revisa las localidades disponibles.",
      "El listado está visible.",
      "configuracion.localidades.listado",
      "lectura",
    ),
    paso(
      "operacion-auditoria",
      "Abre Auditoría",
      "Configuración → Auditoría",
      "La auditoría es de lectura; no corrige datos eliminando historial.",
      "Ejemplo: busca el movimiento que cambió una localidad.",
      "Pulsa Auditoría.",
      "La tabla de movimientos está visible.",
      "configuracion.auditoria.tab",
      "click",
    ),
    paso(
      "operacion-detalle",
      "Abre el detalle",
      "Auditoría → Ver detalle",
      "Confirma usuario, fecha, entidad y acción antes de interpretar el cambio.",
      "Ejemplo: LOCALIDAD · ACTUALIZAR · usuario administrador.",
      "Pulsa Ver detalle en un movimiento.",
      "Se despliegan los valores antes y después.",
      "configuracion.auditoria.detalle",
      "click",
    ),
    paso(
      "operacion-comparar",
      "Compara antes y después",
      "Auditoría → detalle expandido",
      "Una corrección genera un movimiento nuevo; el histórico anterior permanece.",
      "Ejemplo: antes estado=Puebla; después estado=Tlaxcala.",
      "Revisa los dos bloques JSON.",
      "Los valores anteriores y posteriores están visibles.",
      "configuracion.auditoria.valores",
      "lectura",
    ),
  ],
});
