import { definirLeccionWeb, paso } from "./definirLeccion";

export const cortesLiquidacion = definirLeccionWeb({
  id: "cortes-liquidacion",
  pantalla: "cortes",
  roles: ["ADMINISTRADOR", "CONTABLE", "COBRADOR"],
  titulo: ["Corte y liquidación de caja", "Cash closing and settlement"],
  objetivo: [
    "Cuadrar métodos de pago, entregas y reembolsos del operador.",
    "Reconcile payment methods, deliveries, and refunds for the operator.",
  ],
  resultado: [
    "Cierre firmado con diferencias visibles y sin movimientos omitidos.",
    "Signed closing with visible differences and no missing movements.",
  ],
  responsable: [
    "Administración · Contabilidad · Cobranza",
    "Administration · Accounting · Collections",
  ],
  rutaReal: "/cortes",
  guion: [
    paso(
      "corte-operador",
      "Elige al responsable",
      "Corte de caja → Cobrador / responsable",
      "El corte pertenece a quien manejó el dinero.",
      "Ejemplo: Laura Gómez, no el administrador que revisa.",
      "Selecciona al operador.",
      "El filtro conserva al operador.",
      "cortes.operador",
      "select",
    ),
    paso(
      "corte-fecha",
      "Elige la fecha operativa",
      "Corte de caja → Fecha operativa",
      "Usa el día de los movimientos que vas a cuadrar.",
      "Ejemplo: 25/08/2026.",
      "Selecciona la fecha.",
      "La fecha queda aplicada.",
      "cortes.fecha",
      "input",
    ),
    paso(
      "corte-recalcular",
      "Recalcula el corte",
      "Corte de caja → Recalcular",
      "Actualiza antes de contar para incluir los movimientos confirmados.",
      "Ejemplo: hazlo después del último abono de la jornada.",
      "Pulsa Recalcular.",
      "Los indicadores se actualizan.",
      "cortes.recalcular",
      "click",
    ),
    paso(
      "corte-abrir",
      "Abre Firmar cierre",
      "Corte de caja → Firmar cierre",
      "Revisa primero los totales esperados por método.",
      "Ejemplo: efectivo esperado $1,250 y transferencia $600.",
      "Pulsa Firmar cierre.",
      "Se abre Cerrar jornada.",
      "cortes.cierre.abrir",
      "click",
    ),
    paso(
      "corte-efectivo",
      "Declara el efectivo",
      "Cerrar jornada → efectivo",
      "Cuenta físicamente billetes y monedas.",
      "Ejemplo: $1,250.00 contados dos veces.",
      "Escribe el efectivo entregado.",
      "El monto es válido.",
      "cortes.cierre.declarado.efectivo",
      "input",
    ),
    paso(
      "corte-transferencia",
      "Declara transferencias",
      "Cerrar jornada → transferencia",
      "Usa comprobantes conciliados, no mensajes sin verificar.",
      "Ejemplo: $600.00 en comprobantes válidos.",
      "Escribe el total de transferencias.",
      "El monto es válido.",
      "cortes.cierre.declarado.transferencia",
      "input",
    ),
    paso(
      "corte-tarjeta",
      "Declara tarjeta",
      "Cerrar jornada → tarjeta",
      "Usa los vouchers o movimientos confirmados.",
      "Ejemplo: $350.00.",
      "Escribe el total de tarjeta.",
      "El monto es válido.",
      "cortes.cierre.declarado.tarjeta",
      "input",
    ),
    paso(
      "corte-otro",
      "Declara otros métodos",
      "Cerrar jornada → otro",
      "Incluye únicamente métodos que no pertenecen a las categorías anteriores.",
      "Ejemplo: $0.00 si no hubo otro método.",
      "Escribe el total correspondiente.",
      "El monto es válido.",
      "cortes.cierre.declarado.otro",
      "input",
    ),
    paso(
      "corte-firma",
      "Captura la firma",
      "Cerrar jornada → Nombre completo de quien firma",
      "Debe firmar la persona responsable del corte.",
      "Ejemplo: Laura Gómez Hernández.",
      "Escribe el nombre completo.",
      "La firma cumple la longitud requerida.",
      "cortes.cierre.firma",
      "input",
    ),
    paso(
      "corte-frase",
      "Confirma la fecha exacta",
      "Cerrar jornada → Confirmación exacta",
      "Copia la frase mostrada para evitar cerrar el día equivocado.",
      "Ejemplo: CERRAR 2026-08-25.",
      "Escribe la confirmación exacta que muestra el formulario.",
      "La confirmación coincide.",
      "cortes.cierre.confirmacion",
      "input",
    ),
    paso(
      "corte-guardar",
      "Firma y cierra",
      "Cerrar jornada → Firmar y cerrar",
      "Revisa esperados, declarados, diferencia, firma y fecha.",
      "Ejemplo: si hay diferencia, explíquela en Notas antes de cerrar.",
      "Pulsa Firmar y cerrar.",
      "El corte queda simulado sólo en este navegador.",
      "cortes.cierre.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/cortes" },
    ),
  ],
});
