import { definirLeccionWeb, paso } from "./definirLeccion";

export const devolucionRevisarAlmacen = definirLeccionWeb({
  id: "devolucion-revisar-almacen",
  pantalla: "devoluciones",
  roles: ["ALMACENISTA"],
  titulo: ["Revisar mercancía devuelta", "Inspect returned goods"],
  objetivo: [
    "Consultar una devolución ya autorizada y abrir su evidencia sin modificar decisiones financieras.",
    "Review an already authorized return and open its evidence without changing financial decisions.",
  ],
  resultado: [
    "Folio, venta, cliente, motivo, ajustes y evidencia quedan revisados desde el listado.",
    "Receipt, sale, customer, reason, adjustments, and evidence are reviewed from the list.",
  ],
  responsable: ["Almacén", "Warehouse"],
  rutaReal: "/devoluciones",
  guion: [
    paso(
      "almacen-buscar",
      "Busca el movimiento",
      "Devoluciones → Folio, venta o cliente",
      "Almacén puede consultar el registro y su evidencia; no autoriza decisiones financieras.",
      "Ejemplo: busca VEN-1042.",
      "Escribe folio, venta o cliente.",
      "El buscador contiene un valor.",
      "devoluciones.listado.buscar",
      "input",
    ),
    paso(
      "almacen-consultar",
      "Consulta la devolución",
      "Devoluciones → Buscar",
      "Confirma el dato capturado.",
      "Ejemplo: folio completo y sin espacios extra.",
      "Pulsa Buscar.",
      "La lista se actualiza.",
      "devoluciones.listado.buscar-boton",
      "click",
    ),
    paso(
      "almacen-revisar",
      "Revisa el registro disponible",
      "Devoluciones → fila encontrada",
      "Compara folio, cliente, tipo, motivo y fecha con la mercancía recibida.",
      "Ejemplo: si el motivo dice defecto de costura, la pieza física debe corresponder.",
      "Revisa la fila de la devolución.",
      "El movimiento está visible sin controles de autorización.",
      "devoluciones.listado.registro",
      "lectura",
    ),
    paso(
      "almacen-evidencia",
      "Abre la evidencia",
      "Devoluciones → Evidencia",
      "La pantalla actual permite consultar la fotografía; una discrepancia debe escalarse a Administración o Contabilidad.",
      "Ejemplo: foto y producto físico muestran el mismo defecto.",
      "Pulsa Evidencia.",
      "La evidencia se abre sin modificar la devolución.",
      "devoluciones.evidencia",
      "click",
    ),
  ],
});
