import { definirLeccionWeb, paso } from "./definirLeccion";

export const devolucionesSeguras = definirLeccionWeb({
  id: "devoluciones-seguras",
  pantalla: "devoluciones",
  roles: ["ADMINISTRADOR", "CONTABLE"],
  titulo: [
    "Devolución sin borrar historial",
    "Return without deleting history",
  ],
  objetivo: [
    "Autorizar, documentar y regresar inventario correctamente.",
    "Authorize, document, and return stock correctly.",
  ],
  resultado: [
    "Venta y abonos conservan historia; saldo, caja e inventario quedan compensados.",
    "Sale and payments retain history; balance, cash, and inventory are compensated.",
  ],
  responsable: ["Administración · Contabilidad", "Administration · Accounting"],
  tipoSimulador: "DEVOLUCION",
  rutaReal: "/devoluciones",
  guion: [
    paso(
      "devolucion-abrir",
      "Abre Registrar devolución",
      "Devoluciones → Devolución",
      "Una devolución debe partir de una venta confirmada.",
      "Ejemplo: folio VEN-1042.",
      "Pulsa Devolución.",
      "Se abre Registrar devolución.",
      "devoluciones.nueva.abrir",
      "click",
    ),
    paso(
      "devolucion-buscar",
      "Busca la venta",
      "Registrar devolución → Buscar venta confirmada",
      "Usa folio o cliente y confirma la operación original.",
      "Ejemplo: VEN-1042 o Ana López.",
      "Escribe el dato de búsqueda.",
      "El buscador contiene un valor.",
      "devoluciones.venta.buscar",
      "input",
    ),
    paso(
      "devolucion-elegir",
      "Selecciona la venta",
      "Ventas encontradas → resultado",
      "Compara cliente, fecha, total y artículos.",
      "Ejemplo: Ana López · VEN-1042 · $1,200.",
      "Pulsa la venta correcta.",
      "La venta y sus artículos aparecen en el formulario.",
      "devoluciones.venta.elegir",
      "click",
    ),
    paso(
      "devolucion-tipo",
      "Elige el tipo",
      "Registrar devolución → tipo de reversa",
      "En este ejercicio usa Parcial para regresar una parte de la venta.",
      "Ejemplo: devuelve 1 de 2 colchas.",
      "Selecciona Parcial.",
      "El formulario conserva el tipo elegido.",
      "devoluciones.tipo.parcial",
      "click",
    ),
    paso(
      "devolucion-cantidad",
      "Captura la cantidad",
      "Artículo → cantidad a devolver",
      "Nunca excedas la cantidad vendida menos devoluciones previas.",
      "Ejemplo: 1 de 2 piezas disponibles.",
      "Escribe la cantidad.",
      "La cantidad es válida.",
      "devoluciones.cantidad",
      "input",
      undefined,
      { numeroMinimo: 1 },
    ),
    paso(
      "devolucion-motivo",
      "Describe el motivo",
      "Registrar devolución → Motivo detallado",
      "Explica el estado del producto sin frases genéricas.",
      "Ejemplo: costura abierta en esquina superior al desempacar.",
      "Escribe el motivo detallado.",
      "El motivo cumple la longitud requerida.",
      "devoluciones.motivo",
      "input",
    ),
    paso(
      "devolucion-foto",
      "Adjunta evidencia",
      "Registrar devolución → Fotografía de evidencia",
      "La foto debe corresponder al producto y al daño descrito.",
      "Ejemplo: acercamiento del defecto y vista completa de la pieza.",
      "Selecciona una fotografía de práctica.",
      "El formulario conserva la evidencia.",
      "devoluciones.foto",
      "upload",
    ),
    paso(
      "devolucion-confirmar",
      "Confirma la reversa",
      "Registrar devolución → Confirmar reversa",
      "Revisa venta, tipo, cantidades, motivo y evidencia; el historial nunca se borra.",
      "Ejemplo: VEN-1042 · parcial · 1 pieza · defecto documentado.",
      "Pulsa Confirmar reversa.",
      "La reversa queda simulada sólo en este navegador.",
      "devoluciones.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/devoluciones" },
    ),
  ],
});
