import { definirLeccionWeb, paso } from "./definirLeccion";

export const inventarioProducto = definirLeccionWeb({
  id: "inventario-producto",
  pantalla: "inventario",
  roles: ["ADMINISTRADOR", "ALMACENISTA"],
  titulo: ["Alta y fotografía de producto", "Create and photograph a product"],
  objetivo: [
    "Registrar un artículo identificable antes de comprarlo, pedirlo o venderlo.",
    "Register an identifiable item before purchasing, ordering, or selling it.",
  ],
  resultado: [
    "Producto con código, precios, existencia y foto optimizada.",
    "Product with code, prices, stock, and optimized photo.",
  ],
  responsable: ["Administración · Almacén", "Administration · Warehouse"],
  rutaReal: "/inventario",
  guion: [
    paso(
      "producto-buscar",
      "Comprueba el catálogo",
      "Inventario → buscador",
      "Busca nombre, SKU o código antes de crear un producto.",
      "Ejemplo: busca COL-MAT-01.",
      "Escribe un identificador del producto.",
      "El buscador contiene un valor.",
      "inventario.busqueda.campo",
      "input",
    ),
    paso(
      "producto-buscar-boton",
      "Consulta duplicados",
      "Inventario → Buscar",
      "Compara código y nombre en los resultados.",
      "Ejemplo: mismo SKU significa que debes editar el producto existente.",
      "Pulsa Buscar.",
      "La lista se actualiza.",
      "inventario.busqueda.ejecutar",
      "click",
    ),
    paso(
      "producto-nuevo",
      "Abre Nuevo producto",
      "Inventario → Nuevo producto",
      "Hazlo únicamente si el producto no existe.",
      "Ejemplo: una nueva medida con SKU distinto sí requiere alta.",
      "Pulsa Nuevo producto.",
      "Se abre el formulario del producto.",
      "inventario.producto.abrir",
      "click",
    ),
    paso(
      "producto-foto",
      "Agrega una fotografía",
      "Nuevo producto → Fotografía",
      "Usa una imagen clara del artículo, sin datos personales.",
      "Ejemplo: producto completo, fondo neutro y buena luz.",
      "Selecciona una fotografía de práctica.",
      "El formulario muestra la fotografía elegida.",
      "inventario.producto.foto.abrir-selector",
      "upload",
    ),
    paso(
      "producto-nombre",
      "Captura el nombre",
      "Nuevo producto → Nombre del producto",
      "Describe el artículo y su medida principal.",
      "Ejemplo: Colcha matrimonial reversible.",
      "Escribe el nombre.",
      "El nombre es válido.",
      "inventario.producto.nombre",
      "input",
    ),
    paso(
      "producto-categoria",
      "Elige el tipo",
      "Nuevo producto → Tipo o categoría",
      "Reutiliza un tipo existente o escribe uno nuevo si realmente no existe.",
      "Ejemplo: Colcha.",
      "Escribe o elige el tipo.",
      "El tipo queda capturado.",
      "inventario.producto.categoria",
      "input",
    ),
    paso(
      "producto-marca",
      "Captura la marca",
      "Nuevo producto → Marca",
      "Usa la marca impresa en el producto o empaque.",
      "Ejemplo: Nube Hogar.",
      "Escribe la marca.",
      "La marca no está vacía.",
      "inventario.producto.marca",
      "input",
    ),
    paso(
      "producto-sku",
      "Captura el SKU",
      "Nuevo producto → SKU",
      "El SKU debe ser único y consistente con el catálogo.",
      "Ejemplo: COL-MAT-REV-01.",
      "Escribe el SKU.",
      "El SKU es válido.",
      "inventario.producto.sku",
      "input",
    ),
    paso(
      "producto-continuar-precio",
      "Continúa a precios",
      "Nuevo producto → Continuar",
      "La identidad debe estar completa antes de definir importes.",
      "Ejemplo: Colcha · Nube Hogar · COL-MAT-REV-01.",
      "Pulsa Continuar.",
      "Se abre el paso de costo y precio.",
      "inventario.producto.continuar-1",
      "click",
    ),
    paso(
      "producto-costo",
      "Captura el costo",
      "Nuevo producto → Precio de compra",
      "Usa el costo unitario real, no el precio al cliente.",
      "Ejemplo: $650.00.",
      "Escribe el precio de compra.",
      "El costo es válido y no negativo.",
      "inventario.producto.precio-compra",
      "input",
    ),
    paso(
      "producto-precio",
      "Captura el precio de venta",
      "Nuevo producto → Precio de venta",
      "Verifica que sea el precio autorizado.",
      "Ejemplo: $1,200.00.",
      "Escribe el precio de venta.",
      "El precio es mayor a cero.",
      "inventario.producto.precio-venta",
      "input",
    ),
    paso(
      "producto-continuar-existencia",
      "Continúa a existencia",
      "Nuevo producto → Continuar",
      "Comprueba la utilidad mostrada antes de avanzar.",
      "Ejemplo: costo $650 · venta $1,200 · utilidad $550.",
      "Pulsa Continuar.",
      "Se abre el conteo de existencia.",
      "inventario.producto.continuar-2",
      "click",
    ),
    paso(
      "producto-existencia",
      "Captura la existencia inicial",
      "Nuevo producto → Existencia inicial",
      "Cuenta físicamente las piezas disponibles.",
      "Ejemplo: 5 piezas comprobadas, no 50 por error de teclado.",
      "Escribe la existencia inicial.",
      "La existencia es un número válido.",
      "inventario.producto.existencia-inicial",
      "input",
    ),
    paso(
      "producto-guardar",
      "Crea el producto",
      "Nuevo producto → Crear producto",
      "Revisa foto, nombre, SKU, costo, precio y existencia.",
      "Ejemplo: COL-MAT-REV-01 · costo $650 · venta $1,200 · 5 piezas.",
      "Pulsa Crear producto.",
      "El producto queda simulado sólo en este navegador.",
      "inventario.producto.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/inventario/productos" },
    ),
  ],
});
