import { definirLeccionWeb, paso } from "./definirLeccion";

export const orientacionInicio = definirLeccionWeb({
  id: "orientacion-inicio",
  pantalla: "inicio",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR", "ALMACENISTA", "COBRADOR"],
  titulo: ["Ubícate en Vektra", "Find your way around Vektra"],
  objetivo: [
    "Reconocer el enfoque de tu rol y abrir una tarea desde las acciones rápidas.",
    "Recognize your role focus and open a task from quick actions.",
  ],
  resultado: [
    "Identificas las tareas disponibles para tu rol y entras al módulo correcto.",
    "You identify the tasks available to your role and enter the correct module.",
  ],
  responsable: ["Todos los roles", "All roles"],
  rutaReal: "/inicio",
  guion: [
    paso(
      "reconocer-inicio",
      "Ubica el punto de partida",
      "Inicio → encabezado ¿Qué vas a hacer?",
      "Primero confirma que estás en Inicio. Todavía no abras ningún módulo.",
      "Ejemplo: si hoy cobrarás, primero identifica la acción relacionada con cobranza.",
      "Localiza el encabezado ¿Qué vas a hacer?",
      "El encabezado de Inicio está visible.",
      "inicio.bienvenida",
      "lectura",
    ),
    paso(
      "revisar-enfoque-rol",
      "Lee el enfoque de tu rol",
      "Inicio → mensaje bajo ¿Qué vas a hacer?",
      "El mensaje resume la responsabilidad principal del usuario que inició sesión.",
      "Ejemplo: Cobranza ve rutas y abonos; Almacén ve existencias y pedidos.",
      "Revisa el mensaje asignado a tu rol.",
      "El enfoque del rol está visible.",
      "inicio.enfoque-rol",
      "lectura",
    ),
    paso(
      "revisar-acciones",
      "Compara las tareas disponibles",
      "Inicio → tarjetas de acciones",
      "Lee las tarjetas y relaciona cada una con una tarea; no abras varias por probar.",
      "Ejemplo: para cobrar usa Registrar un abono; para surtir usa Atender pedidos pendientes.",
      "Ubica la tarjeta que corresponde a tu tarea de hoy.",
      "Las acciones autorizadas para tu rol están identificadas.",
      "inicio.acciones-rapidas",
      "lectura",
    ),
    paso(
      "abrir-solo-una-accion",
      "Abre sólo la tarea que vas a realizar",
      "Inicio → tarjeta de la tarea elegida",
      "Selecciona una sola acción. La guía conservará el contexto al entrar al módulo real.",
      "Ejemplo: si recibiste dinero, abre Registrar abono; no Nueva venta.",
      "Pulsa la tarjeta que corresponde a tu tarea real.",
      "Llegaste al módulo elegido y la orientación quedó comprobada.",
      "inicio.accion-disponible",
      "click",
    ),
  ],
});
