import { definirLeccionWeb, paso } from "./definirLeccion";

export const pedidoAsignarProveedor = definirLeccionWeb({
  id: "pedido-asignar-proveedor",
  pantalla: "pedidos",
  roles: ["ADMINISTRADOR", "CONTABLE", "ALMACENISTA"],
  titulo: ["Asignar quién surtirá", "Assign who will supply"],
  objetivo: [
    "Vincular proveedor por artículo antes de pedir mercancía.",
    "Link a supplier to each item before ordering goods.",
  ],
  resultado: [
    "Pedido trazable enviado al proveedor; el cobrador no interviene aquí.",
    "Traceable supplier order; the collector does not intervene here.",
  ],
  responsable: [
    "Administración · Contabilidad · Almacén",
    "Administration · Accounting · Warehouse",
  ],
  rutaReal: "/pedidos",
  guion: [
    paso(
      "pedido-filtrar-pendiente",
      "Filtra lo pendiente",
      "Pedidos → Pendiente de pedir",
      "Trabaja sólo con pedidos que aún no tienen proveedor.",
      "Ejemplo: no abras uno ya Recibido en almacén.",
      "Pulsa Pendiente de pedir.",
      "La lista muestra el estado seleccionado.",
      "pedidos.filtro.PENDIENTE_PEDIR",
      "click",
    ),
    paso(
      "pedido-abrir-proveedor",
      "Abre la asignación",
      "Pedido pendiente → Elegir proveedor y pedir",
      "Confirma folio, cliente y artículos antes de asignar.",
      "Ejemplo: PED-104 · Ana López · 2 colchas.",
      "Pulsa Elegir proveedor y pedir.",
      "Se abre Pedir a proveedor.",
      "pedidos.proveedor.abrir",
      "click",
    ),
    paso(
      "pedido-elegir-proveedor",
      "Elige quién surtirá",
      "Pedir a proveedor → artículo → proveedor",
      "Selecciona el proveedor real de esa línea.",
      "Ejemplo: Textiles del Centro para la colcha; no el primero de la lista.",
      "Selecciona el proveedor de cada artículo.",
      "Cada línea conserva un proveedor.",
      "pedidos.proveedor.seleccionar",
      "select",
      undefined,
      { requerirTodosValidos: true },
    ),
    paso(
      "pedido-confirmar-proveedor",
      "Confirma el pedido",
      "Pedir a proveedor → Confirmar pedido al proveedor",
      "Todas las líneas deben tener proveedor antes de continuar.",
      "Ejemplo: 2 de 2 líneas asignadas.",
      "Pulsa Confirmar pedido al proveedor.",
      "El cambio de estado queda sólo en este navegador.",
      "pedidos.proveedor.confirmar",
      "mutacion-local",
      { metodo: "PATCH", ruta: "/pedidos/:id/estado" },
    ),
  ],
});
