import { definirLeccionWeb, paso } from "./definirLeccion";

export const pedidoCrear = definirLeccionWeb({
  id: "pedido-crear",
  pantalla: "pedidos",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR", "COBRADOR"],
  titulo: ["Crear un pedido pendiente", "Create a pending order"],
  objetivo: [
    "Documentar lo que pide el cliente usando productos registrados.",
    "Record what the customer requests using registered products.",
  ],
  resultado: [
    "Queda una solicitud pendiente sin inventar productos ni deuda todavía.",
    "A pending request is created without inventing products or debt yet.",
  ],
  responsable: [
    "Administración · Contabilidad · Ventas · Cobranza",
    "Administration · Accounting · Sales · Collections",
  ],
  rutaReal: "/pedidos",
  guion: [
    paso(
      "pedido-nuevo",
      "Abre Nuevo pedido",
      "Pedidos → Pedido",
      "Un pedido documenta una solicitud; todavía no crea venta ni saldo.",
      "Ejemplo: la clienta pide una colcha que hoy no llevas.",
      "Pulsa Pedido.",
      "Se abre Nuevo pedido.",
      "pedidos.nuevo.abrir",
      "click",
    ),
    paso(
      "pedido-cliente-buscar",
      "Busca al cliente",
      "Nuevo pedido → Cliente",
      "Confirma quién recibirá la mercancía.",
      "Ejemplo: busca por teléfono 2225550147.",
      "Escribe el dato de búsqueda.",
      "El buscador contiene un valor.",
      "pedidos.cliente.buscar",
      "input",
    ),
    paso(
      "pedido-cliente-elegir",
      "Selecciona al cliente",
      "Cliente → resultados",
      "Compara teléfono y localidad.",
      "Ejemplo: Ana López · Centro.",
      "Pulsa la coincidencia correcta.",
      "El cliente queda seleccionado.",
      "pedidos.cliente.opcion",
      "click",
    ),
    paso(
      "pedido-continuar-producto",
      "Continúa al producto",
      "Nuevo pedido → Continuar",
      "Avanza sólo después de comprobar la identidad del cliente.",
      "Ejemplo: Ana López · Centro.",
      "Pulsa Continuar.",
      "Se abre el paso del producto.",
      "pedidos.nuevo.continuar-1",
      "click",
    ),
    paso(
      "pedido-producto-buscar",
      "Busca el producto",
      "Nuevo pedido → Producto registrado",
      "Todo pedido debe usar un producto del catálogo.",
      "Ejemplo: SKU COL-MAT-01.",
      "Escribe nombre, marca, SKU o código.",
      "El buscador contiene un valor.",
      "pedidos.producto.buscar",
      "input",
    ),
    paso(
      "pedido-producto-elegir",
      "Selecciona el producto",
      "Producto registrado → resultados",
      "Compara nombre, SKU y precio automático.",
      "Ejemplo: Colcha matrimonial · COL-MAT-01.",
      "Pulsa el producto correcto.",
      "El producto queda seleccionado.",
      "pedidos.producto.opcion",
      "click",
    ),
    paso(
      "pedido-cantidad",
      "Captura la cantidad",
      "Nuevo pedido → Cantidad",
      "Escribe únicamente las piezas solicitadas.",
      "Ejemplo: 2, no 20.",
      "Cambia la cantidad.",
      "La cantidad es un entero mayor a cero.",
      "pedidos.nuevo.cantidad",
      "input",
    ),
    paso(
      "pedido-continuar-revision",
      "Revisa la solicitud",
      "Nuevo pedido → Continuar",
      "Verifica producto, SKU, cantidad y precio estimado.",
      "Ejemplo: 2 × COL-MAT-01.",
      "Pulsa Continuar.",
      "Se abre la revisión y fecha promesa.",
      "pedidos.nuevo.continuar-2",
      "click",
    ),
    paso(
      "pedido-fecha",
      "Define la fecha compromiso",
      "Nuevo pedido → Fecha compromiso",
      "Usa una fecha acordada; no prometas una llegada no confirmada.",
      "Ejemplo: próximo viernes confirmado con la clienta.",
      "Selecciona la fecha compromiso.",
      "La fecha queda capturada.",
      "pedidos.nuevo.fecha-compromiso",
      "input",
    ),
    paso(
      "pedido-guardar",
      "Guarda el pedido",
      "Nuevo pedido → Guardar",
      "Revisa cliente, producto, cantidad y fecha.",
      "Ejemplo: Ana López · 2 colchas · viernes.",
      "Pulsa Guardar.",
      "El pedido queda simulado sólo en este navegador.",
      "pedidos.nuevo.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/pedidos" },
    ),
  ],
});
