import { definirLeccionWeb, paso } from "./definirLeccion";

export const pedidoRecibirPreparar = definirLeccionWeb({
  id: "pedido-recibir-preparar",
  pantalla: "pedidos",
  roles: ["ADMINISTRADOR", "ALMACENISTA"],
  titulo: ["Recibir y preparar pedido", "Receive and prepare an order"],
  objetivo: [
    "Confirmar llegada y dejar mercancía lista para entregar.",
    "Confirm arrival and prepare goods for delivery.",
  ],
  resultado: [
    "Almacén deja el pedido listo sin crear todavía venta ni saldo.",
    "Warehouse leaves the order ready without creating a sale or balance yet.",
  ],
  responsable: ["Administración · Almacén", "Administration · Warehouse"],
  rutaReal: "/pedidos",
  guion: [
    paso(
      "pedido-filtrar-proveedor",
      "Muestra lo pedido al proveedor",
      "Pedidos → Pedido al proveedor",
      "Compara físicamente artículos y cantidades antes de marcar recepción.",
      "Ejemplo: deben llegar 2 colchas del folio PED-104.",
      "Pulsa Pedido al proveedor.",
      "La lista queda filtrada.",
      "pedidos.filtro.PEDIDO_PROVEEDOR",
      "click",
    ),
    paso(
      "pedido-revisar-articulos",
      "Compara antes de recibir",
      "Pedido al proveedor → artículos",
      "Cuenta físicamente cada artículo y compáralo con la cantidad mostrada. Todavía no cambies el estado.",
      "Ejemplo: la tarjeta dice 2 colchas y tienes exactamente 2 piezas sin daño.",
      "Revisa los artículos y cantidades del pedido.",
      "La relación de artículos está visible para compararla.",
      "pedidos.tarjeta.articulos",
      "lectura",
    ),
    paso(
      "pedido-abrir-recepcion",
      "Abre la revisión de recepción",
      "Pedido al proveedor → Revisar recepción",
      "Hazlo sólo cuando el físico coincide con el pedido.",
      "Ejemplo: llegaron 2 de 2 piezas sin daño.",
      "Pulsa Revisar recepción.",
      "Se abre la comprobación física.",
      "pedidos.almacen.avanzar.PEDIDO_PROVEEDOR",
      "click",
    ),
    paso(
      "pedido-verificar-recepcion",
      "Confirma el conteo",
      "Revisar recepción → artículo",
      "Marca cada renglón contado físicamente.",
      "Ejemplo: 2 piezas mostradas y 2 piezas recibidas.",
      "Marca el artículo.",
      "El artículo queda verificado.",
      "pedidos.almacen.articulo-verificado",
      "click",
    ),
    paso(
      "pedido-marcar-recibido",
      "Confirma la recepción",
      "Revisar recepción → Confirmar recepción física",
      "Este paso cambia el estado; no suma inventario.",
      "Ejemplo: la compra se registra por separado si llegó mercancía nueva.",
      "Pulsa Confirmar recepción física.",
      "La recepción se simula localmente.",
      "pedidos.almacen.confirmar-avance",
      "mutacion-local",
      { metodo: "PATCH", ruta: "/pedidos/:id/estado" },
    ),
    paso(
      "pedido-listo",
      "Déjalo listo para entregar",
      "Pedido recibido → Listo para entrega",
      "Separa y etiqueta el paquete antes de cambiar el estado.",
      "Ejemplo: paquete PED-104 separado para Ana López.",
      "Pulsa Revisar paquete.",
      "Se abre la comprobación del paquete.",
      "pedidos.almacen.avanzar.RECIBIDO_ALMACEN",
      "click",
      undefined,
      { usarEntidadActiva: true },
    ),
    paso(
      "pedido-verificar-paquete",
      "Confirma el paquete",
      "Revisar paquete → artículo",
      "Marca cada artículo separado y etiquetado.",
      "Ejemplo: paquete PED-104 completo.",
      "Marca el artículo.",
      "El artículo queda verificado.",
      "pedidos.almacen.articulo-verificado",
      "click",
    ),
    paso(
      "pedido-confirmar-listo",
      "Déjalo listo",
      "Revisar paquete → Confirmar paquete listo",
      "Aún no se crea venta ni saldo.",
      "Ejemplo: paquete listo para que Cobranza lo entregue.",
      "Pulsa Confirmar paquete listo.",
      "El estado final se simula sólo en este navegador.",
      "pedidos.almacen.confirmar-avance",
      "mutacion-local",
      { metodo: "PATCH", ruta: "/pedidos/:id/estado" },
    ),
  ],
});
