import { definirLeccionWeb, paso } from "./definirLeccion";

export const pedidoEntregar = definirLeccionWeb({
  id: "pedido-entregar",
  pantalla: "pedidos",
  roles: ["ADMINISTRADOR", "COBRADOR"],
  titulo: [
    "Entregar pedido y generar venta",
    "Deliver an order and create the sale",
  ],
  objetivo: [
    "Entregar sólo mercancía lista y definir contado o crédito.",
    "Deliver only ready goods and choose cash or credit.",
  ],
  resultado: [
    "Se crea la venta, baja inventario y el crédito aumenta el saldo financiado.",
    "The sale is created, stock decreases, and credit adds the financed balance.",
  ],
  responsable: ["Administración · Cobranza", "Administration · Collections"],
  tipoSimulador: "ENTREGA_PEDIDO",
  rutaReal: "/pedidos",
  guion: [
    paso(
      "entrega-filtrar",
      "Muestra pedidos listos",
      "Pedidos → Listo para entregar",
      "Entrega únicamente mercancía que Almacén dejó lista.",
      "Ejemplo: PED-104 debe decir Listo para entregar.",
      "Pulsa Listo para entregar.",
      "La lista queda filtrada.",
      "pedidos.filtro.LISTO_ENTREGA",
      "click",
    ),
    paso(
      "entrega-abrir",
      "Abre la entrega",
      "Pedido listo → Entregar",
      "Confirma cliente, folio, artículos y trazabilidad del surtido.",
      "Ejemplo: PED-104 · Ana López · 2 colchas.",
      "Pulsa Entregar.",
      "Se abre Entregar pedido.",
      "pedidos.entrega.abrir",
      "click",
    ),
    paso(
      "entrega-verificar-articulo",
      "Verifica el paquete",
      "Entregar pedido → artículos",
      "Marca el artículo sólo después de verlo físicamente.",
      "Ejemplo: 2 colchas completas y etiquetadas para Ana López.",
      "Marca el artículo verificado.",
      "El renglón queda confirmado.",
      "pedidos.entrega.articulo-verificado",
      "click",
    ),
    paso(
      "entrega-continuar-cobro",
      "Continúa al cobro",
      "Entregar pedido → Continuar",
      "No captures dinero hasta confirmar el paquete.",
      "Ejemplo: cliente y 2 piezas verificados.",
      "Pulsa Continuar.",
      "Se abre el paso de cobro.",
      "pedidos.entrega.continuar-1",
      "click",
    ),
    paso(
      "entrega-tipo",
      "Elige crédito",
      "Entregar pedido → Tipo de venta",
      "En este ejercicio practicarás una entrega con saldo financiado.",
      "Ejemplo: total $1,200, anticipo $300, saldo $900.",
      "Selecciona Crédito.",
      "El formulario muestra los campos del plan.",
      "pedidos.entrega.tipo-credito",
      "click",
    ),
    paso(
      "entrega-anticipo",
      "Captura el anticipo",
      "Entregar pedido → Anticipo",
      "Registra sólo lo recibido en ese momento.",
      "Ejemplo: $300.",
      "Escribe el anticipo.",
      "El anticipo es válido.",
      "pedidos.entrega.anticipo",
      "input",
    ),
    paso(
      "entrega-tarjeta",
      "Captura la tarjeta",
      "Entregar pedido → Número de tarjeta",
      "Usa el número asignado manualmente por el negocio.",
      "Ejemplo: NX-2048.",
      "Escribe el número de tarjeta.",
      "La tarjeta queda capturada.",
      "pedidos.entrega.numero-tarjeta",
      "input",
    ),
    paso(
      "entrega-periodicidad",
      "Elige la periodicidad",
      "Entregar pedido → Periodicidad",
      "Debe coincidir con el acuerdo de cobranza.",
      "Ejemplo: SEMANAL.",
      "Selecciona la periodicidad.",
      "El selector conserva la opción elegida.",
      "pedidos.entrega.periodicidad",
      "select",
    ),
    paso(
      "entrega-cuota",
      "Captura la cuota",
      "Entregar pedido → Monto por cuota",
      "Usa un monto acordado y mayor a cero.",
      "Ejemplo: $150 por semana.",
      "Escribe el monto por cuota.",
      "La cuota es válida.",
      "pedidos.entrega.cuota",
      "input",
    ),
    paso(
      "entrega-fecha",
      "Define el primer vencimiento",
      "Entregar pedido → Primer vencimiento",
      "Usa la primera fecha acordada.",
      "Ejemplo: el próximo martes.",
      "Selecciona la fecha.",
      "La fecha queda capturada.",
      "pedidos.entrega.fecha",
      "input",
    ),
    paso(
      "entrega-continuar-confirmacion",
      "Revisa los efectos",
      "Entregar pedido → Continuar",
      "Comprueba cuánto entra hoy y cuánto se agregará al saldo.",
      "Ejemplo: $300 recibido · $900 financiado.",
      "Pulsa Continuar.",
      "Se abre la revisión final.",
      "pedidos.entrega.continuar-2",
      "click",
    ),
    paso(
      "entrega-confirmar",
      "Confirma entrega y venta",
      "Entregar pedido → Confirmar entrega y venta",
      "Revisa tipo, anticipo, tarjeta, periodicidad y cuota.",
      "Ejemplo: $1,200 − $300 = $900 financiados.",
      "Pulsa Confirmar entrega y venta.",
      "La entrega queda simulada sólo en este navegador.",
      "pedidos.entrega.confirmar",
      "mutacion-local",
      { metodo: "POST", ruta: "/pedidos/:id/entregar" },
    ),
  ],
});
