import { definirLeccionWeb, paso } from "./definirLeccion";

export const reportesBalance = definirLeccionWeb({
  id: "reportes-balance",
  pantalla: "reportes",
  roles: ["ADMINISTRADOR", "CONTABLE"],
  titulo: [
    "Definir rangos y exportar reportes",
    "Set ranges and export reports",
  ],
  objetivo: [
    "Definir el rango de ventas y usar las exportaciones reales de ventas, cartera y pedidos.",
    "Set the sales date range and use the actual sales, receivables, and order exports.",
  ],
  resultado: [
    "Obtienes ventas y utilidad en Excel para el rango elegido, cartera en Excel y pendientes en PDF.",
    "You obtain sales and profit in Excel for the selected range, receivables in Excel, and pending orders in PDF.",
  ],
  responsable: ["Administración · Contabilidad", "Administration · Accounting"],
  rutaReal: "/reportes",
  guion: [
    paso(
      "reportes-desde",
      "Define la fecha inicial",
      "Reportes → Desde",
      "La pantalla usa fechas exactas; no existe un selector semestral.",
      "Ejemplo: 01/01/2026 para iniciar el semestre.",
      "Selecciona la fecha inicial.",
      "La fecha queda aplicada.",
      "reportes.desde",
      "input",
    ),
    paso(
      "reportes-hasta",
      "Define la fecha final",
      "Reportes → Hasta",
      "La fecha final debe ser igual o posterior a Desde.",
      "Ejemplo: 30/06/2026.",
      "Selecciona la fecha final.",
      "El intervalo es válido.",
      "reportes.hasta",
      "input",
    ),
    paso(
      "reportes-ventas",
      "Exporta ventas y utilidad",
      "Ventas y utilidad → Excel",
      "Este archivo corresponde al periodo exacto elegido.",
      "Ejemplo: usa este Excel para analizar ventas, no para listar cartera.",
      "Pulsa Excel en Ventas y utilidad.",
      "El navegador inicia la descarga correcta.",
      "reportes.ventas.excel",
      "click",
    ),
    paso(
      "reportes-cartera",
      "Exporta cartera",
      "Cartera de clientes → Excel",
      "Cartera es deuda pendiente; no equivale a ventas del periodo.",
      "Ejemplo: una venta a crédito puede aparecer en ventas y seguir en cartera.",
      "Pulsa Excel en Cartera de clientes.",
      "El navegador inicia la descarga de cartera.",
      "reportes.cartera.excel",
      "click",
    ),
    paso(
      "reportes-surtir",
      "Exporta lo pendiente de surtir",
      "Lista para surtir → PDF",
      "Este PDF es operativo y no sustituye los archivos contables.",
      "Ejemplo: úsalo para preparar pedidos pendientes.",
      "Pulsa PDF en Lista para surtir.",
      "El navegador inicia la descarga del PDF.",
      "reportes.surtir.pdf",
      "click",
    ),
  ],
});
