import { definirLeccionWeb, paso } from "./definirLeccion";

export const rutasConfiguracion = definirLeccionWeb({
  id: "rutas-configuracion",
  pantalla: "rutas",
  roles: ["ADMINISTRADOR"],
  titulo: ["Crear y asignar una ruta", "Create and assign a route"],
  objetivo: [
    "Elegir localidades, seleccionar sólo las clientas con saldo y definir manualmente el orden de cobranza.",
    "Choose locations, select only customers with a balance, and manually set collection order.",
  ],
  resultado: [
    "Ruta con responsable, clientas elegidas y el orden exacto en que se cobrarán.",
    "Route with an owner, selected customers, and the exact collection order.",
  ],
  responsable: ["Administración", "Administration"],
  rutaReal: "/rutas",
  guion: [
    paso(
      "ruta-nueva",
      "Abre Nueva ruta",
      "Rutas → Nueva ruta",
      "Antes deben existir localidades, clientas con saldo y un cobrador activo.",
      "Ejemplo: Ruta Centro - Martes.",
      "Pulsa Nueva ruta.",
      "Se abre Nueva ruta de cobranza.",
      "rutas.configuracion.abrir-nueva",
      "click",
    ),
    paso(
      "ruta-nombre",
      "Escribe el nombre",
      "Nueva ruta → Nombre de ruta",
      "Usa zona y día para reconocerla.",
      "Ejemplo: Ruta Centro - Martes.",
      "Captura el nombre.",
      "El nombre es válido.",
      "rutas.configuracion.nombre",
      "input",
    ),
    paso(
      "ruta-dia",
      "Elige el día",
      "Nueva ruta → Día de cobranza",
      "Selecciona el día real de visita.",
      "Ejemplo: MARTES.",
      "Selecciona el día.",
      "El selector conserva el día elegido.",
      "rutas.configuracion.dia",
      "select",
    ),
    paso(
      "ruta-cobrador",
      "Asigna al responsable",
      "Nueva ruta → Cobrador responsable",
      "Elige a quien manejará esa jornada, no a un administrador por comodidad.",
      "Ejemplo: Laura Gómez · cobradora@nexo.local.",
      "Selecciona al cobrador.",
      "El formulario conserva un cobrador activo.",
      "rutas.configuracion.cobrador",
      "select",
    ),
    paso(
      "ruta-buscar-localidad",
      "Busca la localidad",
      "Nueva ruta → 1. Elige las localidades",
      "Incluye sólo zonas que realmente se visitarán.",
      "Ejemplo: Centro; no Norte si no forma parte del recorrido.",
      "Escribe nombre o estado.",
      "El filtro contiene un valor.",
      "rutas.configuracion.localidad-buscar",
      "input",
    ),
    paso(
      "ruta-elegir-localidad",
      "Selecciona la localidad",
      "1. Elige las localidades → resultado",
      "La selección limita qué clientas pueden aparecer.",
      "Ejemplo: Centro · Puebla.",
      "Marca la localidad que sí visitarás.",
      "La localidad queda seleccionada.",
      "rutas.configuracion.localidad-seleccionar",
      "check",
    ),
    paso(
      "ruta-buscar-clienta",
      "Busca una clienta con saldo",
      "2. Selecciona a quién cobrar",
      "Sólo aparecen clientas activas con saldo mayor a cero de las localidades elegidas.",
      "Ejemplo: Ana · saldo $350 sí; Marta · saldo $0 no aparece.",
      "Escribe nombre, tarjeta o localidad.",
      "El filtro contiene un valor.",
      "rutas.configuracion.cliente-buscar",
      "input",
    ),
    paso(
      "ruta-elegir-clienta",
      "Selecciona la primera clienta",
      "2. Selecciona a quién cobrar → resultados",
      "Marca únicamente las clientas de esta jornada; no se agregan automáticamente.",
      "Ejemplo: marca a Ana con saldo $350 si sí forma parte de la jornada.",
      "Pulsa la primera clienta que sí visitarás.",
      "La primera clienta aparece en el orden de visita.",
      "rutas.configuracion.cliente-seleccionar",
      "click",
    ),
    paso(
      "ruta-elegir-segunda-clienta",
      "Selecciona otra clienta para ordenar",
      "2. Selecciona a quién cobrar → resultados",
      "Para practicar el orden necesitas al menos dos clientas con saldo de la localidad elegida.",
      "Ejemplo: después de Ana $350, agrega a Rosa $500; no marques a quien no visitarás.",
      "Pulsa una segunda clienta que sí visitarás.",
      "Las dos clientas aparecen en el orden de visita.",
      "rutas.configuracion.cliente-seleccionar-segunda",
      "click",
      undefined,
      {
        controlesAuxiliares: ["rutas.configuracion.cliente-buscar"],
      },
    ),
    paso(
      "ruta-ordenar",
      "Define el orden",
      "3. Define el orden de visita",
      "El orden debe representar el recorrido decidido por el cobrador.",
      "Ejemplo: Ana → Rosa → Lupe.",
      "En la segunda clienta, pulsa Subir una vez.",
      "El orden cambia mediante el control real.",
      "rutas.configuracion.orden-subir",
      "reordenar",
    ),
    paso(
      "ruta-guardar",
      "Guarda selección y orden",
      "Nueva ruta → Guardar",
      "Revisa nombre, día, responsable, localidades, clientas y orden.",
      "Ejemplo final: Centro · martes · Laura · Ana → Rosa.",
      "Pulsa Guardar.",
      "La ruta queda simulada sólo en este navegador.",
      "rutas.configuracion.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/rutas" },
    ),
  ],
});
