import { definirLeccionWeb, paso } from "./definirLeccion";

export const rutasJornada = definirLeccionWeb({
  id: "rutas-jornada",
  pantalla: "rutas",
  roles: ["ADMINISTRADOR", "COBRADOR"],
  titulo: ["Completar una ruta de cobranza", "Complete a collection route"],
  objetivo: [
    "Registrar resultados y abonos de clientes asignados o extraordinarios.",
    "Record results and payments for assigned or out-of-route customers.",
  ],
  resultado: [
    "La jornada muestra las visitas registradas y las que siguen pendientes.",
    "The workday shows recorded visits and those still pending.",
  ],
  responsable: ["Administración · Cobranza", "Administration · Collections"],
  rutaReal: "/rutas",
  guion: [
    paso(
      "jornada-ruta",
      "Elige la ruta",
      "Rutas → Ruta",
      "Selecciona únicamente una ruta asignada o permitida para tu rol.",
      "Ejemplo: Ruta Centro - Martes.",
      "Selecciona la ruta.",
      "La jornada correspondiente aparece.",
      "rutas.jornada.ruta",
      "select",
    ),
    paso(
      "jornada-fecha",
      "Elige la fecha",
      "Rutas → Fecha de jornada",
      "Usa el día que estás operando.",
      "Ejemplo: 25/08/2026.",
      "Selecciona la fecha.",
      "La fecha queda aplicada.",
      "rutas.jornada.fecha",
      "input",
    ),
    paso(
      "jornada-cliente",
      "Abre una visita",
      "Jornada → clienta asignada",
      "Confirma nombre, tarjeta, localidad y saldo antes de abrir.",
      "Ejemplo: Ana López · NX-2048 · saldo $350.",
      "Pulsa la fila de la clienta correcta.",
      "Se abre el formulario de visita.",
      "rutas.jornada.cliente",
      "click",
    ),
    paso(
      "jornada-resultado",
      "Captura el resultado",
      "Visita → Resultado",
      "Elige lo que realmente ocurrió.",
      "Ejemplo de esta práctica: Pagó porque recibiste y contaste $200.",
      "Selecciona Pagó para practicar el registro de un abono.",
      "El resultado Pagó queda seleccionado y aparece Monto recibido.",
      "rutas.visita.resultado",
      "select",
    ),
    paso(
      "jornada-monto",
      "Captura el monto",
      "Visita → Monto recibido",
      "Sólo aplica si el resultado fue Pagó.",
      "Ejemplo: $200 recibidos y contados.",
      "Escribe el monto recibido.",
      "El monto es válido.",
      "rutas.visita.monto",
      "input",
    ),
    paso(
      "jornada-guardar",
      "Guarda la visita",
      "Visita → Guardar",
      "Revisa clienta, resultado, monto y notas.",
      "Ejemplo: Ana López · Pagó · $200.",
      "Pulsa Guardar.",
      "La visita queda simulada sólo en este navegador.",
      "rutas.visita.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/rutas/:id/visitas" },
    ),
    paso(
      "jornada-extra-buscar",
      "Busca fuera de ruta",
      "Jornada → Fuera de ruta",
      "Este acceso es excepcional y no amplía toda la cartera.",
      "Ejemplo: busca por tarjeta NX-3001.",
      "Escribe nombre, teléfono, dirección o tarjeta.",
      "El buscador contiene un valor.",
      "rutas.extraordinaria.termino",
      "input",
    ),
    paso(
      "jornada-extra-consultar",
      "Consulta la clienta",
      "Fuera de ruta → Buscar clienta",
      "Revisa el dato antes de consultar.",
      "Ejemplo: NX-3001 completo.",
      "Pulsa Buscar clienta.",
      "Aparecen coincidencias autorizadas.",
      "rutas.extraordinaria.buscar",
      "click",
    ),
  ],
});
