import { definirLeccionWeb, paso } from "./definirLeccion";

export const seguridadUsuarios = definirLeccionWeb({
  id: "seguridad-usuarios",
  pantalla: "usuarios",
  roles: ["ADMINISTRADOR"],
  titulo: ["Crear usuarios con mínimo acceso", "Create least-privilege users"],
  objetivo: [
    "Crear una cuenta con nombre, correo, rol y contraseña de acceso.",
    "Create an account with a name, email, role, and sign-in password.",
  ],
  resultado: [
    "La persona puede entrar directamente según su rol; almacén y cobranza usan sólo el móvil.",
    "The person can sign in for their role; warehouse and collections use mobile only.",
  ],
  responsable: ["Administración", "Administration"],
  rutaReal: "/usuarios",
  guion: [
    paso(
      "usuario-nuevo",
      "Abre Nuevo usuario",
      "Usuarios → Nuevo",
      "Crea una cuenta individual; nunca compartas una cuenta administrativa.",
      "Ejemplo: Laura Gómez tendrá su propio correo y rol Cobrador.",
      "Pulsa Nuevo.",
      "Se abre Nuevo usuario.",
      "usuarios.nuevo.abrir",
      "click",
    ),
    paso(
      "usuario-nombre",
      "Captura el nombre",
      "Nuevo usuario → Nombre",
      "Usa el nombre de la persona responsable de la cuenta.",
      "Ejemplo: Laura Gómez Hernández.",
      "Escribe el nombre.",
      "El nombre es válido.",
      "usuarios.nuevo.nombre",
      "input",
    ),
    paso(
      "usuario-correo",
      "Captura el correo",
      "Nuevo usuario → Correo",
      "El correo identifica la cuenta y debe ser único.",
      "Ejemplo: laura.gomez@negocio.mx.",
      "Escribe el correo.",
      "El correo es válido.",
      "usuarios.nuevo.correo",
      "input",
    ),
    paso(
      "usuario-rol",
      "Asigna el rol mínimo",
      "Nuevo usuario → Rol",
      "Elige por tareas reales; no asignes Administrador por comodidad.",
      "Ejemplo: quien cobra rutas usa COBRADOR, no ADMINISTRADOR.",
      "Selecciona el rol.",
      "El selector conserva el rol elegido.",
      "usuarios.nuevo.rol",
      "select",
    ),
    paso(
      "usuario-clave",
      "Genera una contraseña",
      "Nuevo usuario → Generar clave segura",
      "Entrega la clave por un canal seguro. Quedará lista para entrar.",
      "Ejemplo: usa la clave generada, no Nombre2026.",
      "Pulsa Generar clave segura.",
      "El campo contiene una contraseña de acceso.",
      "usuarios.nuevo.generar-clave",
      "click",
    ),
    paso(
      "usuario-guardar",
      "Guarda la cuenta",
      "Nuevo usuario → Guardar",
      "Revisa nombre, correo, rol y contraseña. MFA se configura en el Perfil propio, no en esta pantalla.",
      "Ejemplo: Laura Gómez · COBRADOR · acceso móvil.",
      "Pulsa Guardar.",
      "La cuenta queda simulada sólo en este navegador.",
      "usuarios.nuevo.guardar",
      "mutacion-local",
      { metodo: "POST", ruta: "/usuarios" },
    ),
  ],
});
