import { definirLeccionWeb, paso } from "./definirLeccion";

export const ventasContadoCredito = definirLeccionWeb({
  id: "ventas-contado-credito",
  pantalla: "ventas",
  roles: ["ADMINISTRADOR", "CONTABLE", "VENDEDOR"],
  titulo: ["Venta de contado o a crédito", "Cash or credit sale"],
  objetivo: [
    "Elegir correctamente cómo impactará saldo y caja.",
    "Choose correctly how the sale affects balance and cash.",
  ],
  resultado: [
    "Contado no crea deuda; crédito suma sólo lo financiado al saldo.",
    "Cash creates no debt; credit adds only the financed amount to balance.",
  ],
  responsable: [
    "Administración · Contabilidad · Ventas",
    "Administration · Accounting · Sales",
  ],
  tipoSimulador: "VENTA_CREDITO",
  rutaReal: "/ventas",
  guion: [
    paso(
      "venta-abrir",
      "Abre una venta nueva",
      "Ventas → Nueva venta",
      "No uses Registrar abono: ese botón cobra una deuda existente.",
      "Ejemplo: para entregar un producto nuevo, usa Nueva venta.",
      "Pulsa Nueva venta.",
      "Se abre Registrar venta.",
      "ventas.nueva.abrir",
      "click",
    ),
    paso(
      "venta-tipo",
      "Elige el tipo de venta",
      "Registrar venta → Tipo",
      "En este ejercicio practicarás crédito. Contado cobra el total y no crea deuda.",
      "Ejemplo: total $1,200, anticipo $300 y saldo $900 = crédito.",
      "Pulsa Venta a crédito.",
      "El formulario avanza a Cliente y productos.",
      "ventas.tipo.credito",
      "click",
    ),
    paso(
      "venta-buscar-cliente",
      "Busca al cliente",
      "Cliente y productos → Cliente",
      "Confirma primero quién asumirá el saldo.",
      "Ejemplo: busca Ana o su teléfono 2225550147.",
      "Escribe nombre, teléfono, tarjeta o localidad.",
      "El buscador contiene un valor.",
      "ventas.cliente.buscar",
      "input",
    ),
    paso(
      "venta-elegir-cliente",
      "Selecciona al cliente",
      "Cliente → resultados",
      "Compara teléfono y localidad antes de elegir.",
      "Ejemplo: Ana López · 2225550147 · Centro.",
      "Pulsa la coincidencia correcta.",
      "El cliente queda seleccionado.",
      "ventas.cliente.opcion",
      "click",
    ),
    paso(
      "venta-buscar-producto",
      "Busca el producto",
      "Cliente y productos → Producto registrado",
      "Selecciona sólo mercancía con existencia.",
      "Ejemplo: Colcha matrimonial, SKU COL-MAT-01.",
      "Escribe producto, marca, SKU o código.",
      "El buscador contiene un valor.",
      "ventas.producto.buscar",
      "input",
    ),
    paso(
      "venta-elegir-producto",
      "Agrega el producto",
      "Producto registrado → resultados",
      "Compara nombre, SKU, existencia y precio.",
      "Ejemplo: Colcha matrimonial · 5 en existencia · $1,200.",
      "Pulsa el producto correcto.",
      "El producto aparece en el carrito.",
      "ventas.producto.opcion",
      "click",
    ),
    paso(
      "venta-cantidad",
      "Confirma la cantidad",
      "Carrito → cantidad del producto",
      "La práctica usa la unidad que acabas de agregar; no aumentes si la existencia no alcanza.",
      "Ejemplo: para una colcha entregada, la cantidad correcta es 1.",
      "Revisa la cantidad mostrada en el carrito.",
      "La cantidad disponible queda comprobada antes del resumen.",
      "ventas.carrito.cantidad",
      "lectura",
    ),
    paso(
      "venta-revisar",
      "Pasa al resumen",
      "Cliente y productos → Revisar venta",
      "Confirma cliente, productos y subtotal antes de avanzar.",
      "Ejemplo: Ana López · 1 colcha · subtotal $1,200.",
      "Pulsa Revisar venta.",
      "Aparece Cobro y confirmación.",
      "ventas.productos.revisar",
      "click",
    ),
    paso(
      "venta-anticipo",
      "Captura el anticipo",
      "Cobro y confirmación → Anticipo recibido",
      "El anticipo reduce lo financiado; nunca registres el total si no lo recibiste.",
      "Ejemplo: de $1,200 recibe $300; quedarán $900 financiados.",
      "Escribe el anticipo recibido.",
      "El anticipo es válido y menor al total financiado.",
      "ventas.cobro.anticipo",
      "input",
    ),
    paso(
      "venta-tarjeta",
      "Captura la tarjeta",
      "Cobro y confirmación → Número de tarjeta",
      "Usa el número asignado por el negocio; no se genera automáticamente.",
      "Ejemplo: NX-2048.",
      "Escribe el número de tarjeta confirmado.",
      "El campo contiene una tarjeta válida.",
      "ventas.credito.tarjeta",
      "input",
    ),
    paso(
      "venta-frecuencia",
      "Elige la frecuencia",
      "Cobro y confirmación → Frecuencia",
      "La frecuencia debe coincidir con el acuerdo de cobro.",
      "Ejemplo: SEMANAL si visitarán cada siete días.",
      "Selecciona la frecuencia acordada.",
      "El selector conserva la frecuencia elegida.",
      "ventas.credito.frecuencia",
      "select",
    ),
    paso(
      "venta-cuota",
      "Captura la cuota",
      "Cobro y confirmación → Cuánto pagará",
      "La cuota debe ser posible para el cliente y mayor a cero.",
      "Ejemplo: $150 semanales para un saldo de $900.",
      "Escribe el monto por cuota.",
      "La cuota es válida.",
      "ventas.credito.cuota",
      "input",
    ),
    paso(
      "venta-primer-cobro",
      "Define el primer cobro",
      "Cobro y confirmación → Primer cobro",
      "Usa la fecha acordada, no la fecha actual por defecto.",
      "Ejemplo: el próximo martes confirmado con la clienta.",
      "Selecciona la fecha del primer cobro.",
      "La fecha es válida.",
      "ventas.credito.primer-cobro",
      "input",
    ),
    paso(
      "venta-confirmar",
      "Confirma la venta",
      "Resumen antes de confirmar → Confirmar venta",
      "Revisa total, anticipo, financiado y saldo nuevo una última vez.",
      "Ejemplo: $1,200 − $300 = $900 financiados.",
      "Pulsa Confirmar venta.",
      "La venta queda simulada sólo en este navegador.",
      "ventas.cobro.confirmar",
      "mutacion-local",
      { metodo: "POST", ruta: "/ventas" },
    ),
  ],
});
