/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/iniciar-sesion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inicia sesión web o móvil */
    post: operations["postAuthIniciarSesion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/renovar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Consume una sola vez el refresh token y rota la sesión
     * @description Web usa cookie+CSRF; móvil envía refreshToken. Renovaciones concurrentes sólo permiten una sucesora.
     */
    post: operations["postAuthRenovar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cerrar-sesion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoca la sesión */
    post: operations["postAuthCerrarSesion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sesion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devuelve la identidad actual */
    get: operations["getAuthSesion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cambiar-contrasena": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cambia contraseña propia y revoca sesiones */
    post: operations["postAuthCambiarContrasena"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/mfa/iniciar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Genera secreto MFA temporal */
    post: operations["postAuthMfaIniciar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/mfa/confirmar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirma MFA con TOTP */
    post: operations["postAuthMfaConfirmar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/mfa/deshabilitar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deshabilita MFA con contraseña y TOTP */
    post: operations["postAuthMfaDeshabilitar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/usuarios": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista usuarios */
    get: operations["getUsuarios"];
    put?: never;
    /** Crea usuario con contraseña temporal y cambio obligatorio */
    post: operations["postUsuarios"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/usuarios/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita rol/estado sin permitir eliminar al último administrador */
    patch: operations["patchUsuariosId"];
    trace?: never;
  };
  "/usuarios/{id}/restablecer-contrasena": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Asigna contraseña temporal, revoca sesiones y fuerza su cambio */
    post: operations["postUsuariosIdRestablecerContrasena"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/clientes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista/busca clientes dentro del alcance */
    get: operations["getClientes"];
    put?: never;
    /** Crea cliente */
    post: operations["postClientes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/clientes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Expediente completo según alcance */
    get: operations["getClientesId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita contacto/localidad y campos permitidos */
    patch: operations["patchClientesId"];
    trace?: never;
  };
  "/clientes/{id}/tarjeta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Asigna tarjeta manual a cliente con saldo */
    patch: operations["patchClientesIdTarjeta"];
    trace?: never;
  };
  "/clientes/{id}/saldo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Ajusta saldo con valor esperado, motivo y contraseña */
    patch: operations["patchClientesIdSaldo"];
    trace?: never;
  };
  "/clientes/{id}/estado-cuenta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Descarga/consulta estado de cuenta */
    get: operations["getClientesIdEstadoCuenta"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/localidades": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista localidades */
    get: operations["getLocalidades"];
    put?: never;
    /** Crea localidad */
    post: operations["postLocalidades"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/localidades/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita localidad */
    patch: operations["patchLocalidadesId"];
    trace?: never;
  };
  "/rutas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista rutas permitidas */
    get: operations["getRutas"];
    put?: never;
    /** Crea ruta multilocalidad, con cobrador móvil opcional */
    post: operations["postRutas"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Reconfigura ruta/asignaciones */
    patch: operations["patchRutasId"];
    trace?: never;
  };
  "/rutas/clientes-con-saldo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista clientas activas con saldo disponibles para asignar y ordenar */
    get: operations["getRutasClientesConSaldo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/visitas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Registra visita en línea */
    post: operations["postRutasIdVisitas"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/directorio-cobranza": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Directorio offline limitado al cobrador */
    get: operations["getRutasDirectorioCobranza"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/clientes-extraordinarios": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Busca clientas de otra ruta del mismo cobrador */
    get: operations["getRutasIdClientesExtraordinarios"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/jornada": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Descarga jornada para trabajo offline */
    get: operations["getRutasIdJornada"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/hoja.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hoja imprimible con orden exacto y monto a cobrar por cliente */
    get: operations["getRutasIdHoja.pdf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/resultado.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reporte PDF con cobros, diferencias y compromisos de la jornada */
    get: operations["getRutasIdResultado.pdf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rutas/{id}/historial": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historial de visitas/abonos */
    get: operations["getRutasIdHistorial"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ventas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista ventas dentro del alcance */
    get: operations["getVentas"];
    put?: never;
    /** Confirma venta de contado o crédito */
    post: operations["postVentas"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ventas/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalle histórico de venta */
    get: operations["getVentasId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/abonos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista abonos permitidos */
    get: operations["getAbonos"];
    put?: never;
    /** Aplica abono a saldo/cuotas/caja */
    post: operations["postAbonos"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/abonos/agenda": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resume qué cobrar hoy, esta semana y lo vencido */
    get: operations["getAbonosAgenda"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/abonos/riesgo/recalcular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recalcula evaluación de riesgo */
    post: operations["postAbonosRiesgoRecalcular"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/abonos/{id}/anular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compensa un abono sin borrarlo */
    post: operations["postAbonosIdAnular"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/productos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista productos; oculta costos por rol */
    get: operations["getInventarioProductos"];
    put?: never;
    /** Crea producto, existencia y foto opcional */
    post: operations["postInventarioProductos"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/catalogos-producto": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista marcas y categorías activas para reutilizarlas al capturar */
    get: operations["getInventarioCatalogosProducto"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/categorias-producto": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Agrega o reactiva una agrupación del catálogo */
    post: operations["postInventarioCategoriasProducto"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/productos/codigo/{codigo}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Busca por código de barras/QR/SKU */
    get: operations["getInventarioProductosCodigoCodigo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/productos/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Baja lógica conservando historial */
    delete: operations["deleteInventarioProductosId"];
    options?: never;
    head?: never;
    /** Edita catálogo/foto */
    patch: operations["patchInventarioProductosId"];
    trace?: never;
  };
  "/inventario/productos/{id}/foto": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Foto privada con ETag */
    get: operations["getInventarioProductosIdFoto"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/productos/{id}/ajuste": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ajuste auditado de existencia */
    post: operations["postInventarioProductosIdAjuste"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/inventario/movimientos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Libro paginado de inventario */
    get: operations["getInventarioMovimientos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/compras": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historial de compras */
    get: operations["getCompras"];
    put?: never;
    /** Registra factura/entrada y aumenta stock */
    post: operations["postCompras"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/proveedores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista fichas de proveedor autorizadas */
    get: operations["getProveedores"];
    put?: never;
    /** Crea proveedor */
    post: operations["postProveedores"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/proveedores/opciones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lista mínima para selectores de pedidos y compras
     * @description Devuelve exclusivamente id y nombre; nunca RFC, contacto, teléfono, correo ni notas.
     */
    get: operations["getProveedoresOpciones"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/proveedores/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita proveedor */
    patch: operations["patchProveedoresId"];
    trace?: never;
  };
  "/pedidos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista pedidos por alcance/cliente */
    get: operations["getPedidos"];
    put?: never;
    /** Captura pedido sólo con productos registrados */
    post: operations["postPedidos"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pedidos/{id}/estado": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Asigna proveedor/avanza surtido */
    patch: operations["patchPedidosIdEstado"];
    trace?: never;
  };
  "/pedidos/{id}/entregar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entrega y crea venta/saldo/stock atómicamente */
    post: operations["postPedidosIdEntregar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devoluciones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista devoluciones según permiso */
    get: operations["getDevoluciones"];
    put?: never;
    /** Autoriza devolución/cambio/reembolso */
    post: operations["postDevoluciones"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devoluciones/{id}/evidencia": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evidencia privada de devolución */
    get: operations["getDevolucionesIdEvidencia"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cortes/operadores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operadores visibles para corte */
    get: operations["getCortesOperadores"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cortes/previsualizar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Calcula corte sin cerrarlo */
    get: operations["getCortesPrevisualizar"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cortes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historial de cortes permitidos */
    get: operations["getCortes"];
    put?: never;
    /** Sella jornada y diferencias de caja */
    post: operations["postCortes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/catalogo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catálogo móvil sin costo */
    get: operations["getSincronizacionCatalogo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/dispositivos/registrar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enrola clave HMAC de dispositivo */
    post: operations["postSincronizacionDispositivosRegistrar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/dispositivos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista dispositivos propios o administrables */
    get: operations["getSincronizacionDispositivos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/dispositivos/{id}/revocar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Revoca dispositivo */
    patch: operations["patchSincronizacionDispositivosIdRevocar"];
    trace?: never;
  };
  "/sincronizacion/dispositivos/{id}/reemplazar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoca un dispositivo y enrola su reemplazo con cadena GENESIS */
    post: operations["postSincronizacionDispositivosIdReemplazar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/revisiones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista recibos offline que necesitan resolución administrativa */
    get: operations["getSincronizacionRevisiones"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sincronizacion/revisiones/{id}/resolver": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Documenta resolución y movimiento compensatorio sin editar el recibo */
    patch: operations["patchSincronizacionRevisionesIdResolver"];
    trace?: never;
  };
  "/sincronizacion/lotes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Procesa 1..500 operaciones encadenadas
     * @description CONFIRMADA aplica efectos. RECHAZADA revierte sólo esa operación, conserva recibo terminal y avanza la cadena. Errores técnicos revierten el lote.
     */
    post: operations["postSincronizacionLotes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reportes/resumen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Balance mes/bimestre/semestre/año */
    get: operations["getReportesResumen"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reportes/ventas.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Excel de ventas con fórmulas */
    get: operations["getReportesVentas.xlsx"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reportes/clientes.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Excel de cartera sin PII de contacto */
    get: operations["getReportesClientes.xlsx"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reportes/pedidos-pendientes.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** PDF de surtido */
    get: operations["getReportesPedidosPendientes.pdf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/alertas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Alertas filtradas por rol/alcance */
    get: operations["getAlertas"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auditoria": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bitácora paginada */
    get: operations["getAuditoria"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/importaciones/plantilla.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Descarga plantilla inicial */
    get: operations["getImportacionesPlantilla.xlsx"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/importaciones/excel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Importa clientes/productos/saldos/localidades/rutas atómicamente */
    post: operations["postImportacionesExcel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reconciliacion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Reconstruye saldos y existencias sin modificar proyecciones
     * @description Devuelve IDs, valores esperados y actuales. Toda corrección posterior debe ser compensatoria y auditada.
     */
    get: operations["getReconciliacion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DineroNoNegativo: number;
    DineroPositivo: number;
    Error: {
      error: {
        codigo: string;
        mensaje: string;
        detalles?: unknown;
      };
    };
    Pagina: {
      datos: unknown[];
      total: number;
      pagina: number;
      limite: number;
      paginas?: number;
    };
    InicioSesion: {
      /** Format: email */
      correo: string;
      contrasena: string;
      /**
       * @default WEB
       * @enum {string}
       */
      cliente: "WEB" | "MOVIL";
      codigoMfa?: string;
    };
    ClienteEntrada: {
      nombreCompleto: string;
      telefono: string;
      direccion: string;
      /** Format: uuid */
      localidadId: string;
      limiteCredito?: components["schemas"]["DineroNoNegativo"];
      notas?: string;
    };
    PlanPago: {
      /** @enum {string} */
      periodicidad: "SEMANAL" | "QUINCENAL" | "MENSUAL";
      montoCuota: components["schemas"]["DineroPositivo"];
      /**
       * Format: date-time
       * @description Igual o posterior a fechaVenta/fechaEntrega
       */
      primerVencimiento: string;
    };
    VentaEntrada: {
      /** Format: uuid */
      clienteId?: string | null;
      numeroTarjeta?: string;
      /** @enum {string} */
      tipo: "CONTADO" | "CREDITO" | "PUBLICO";
      descuento?: components["schemas"]["DineroNoNegativo"];
      anticipo?: components["schemas"]["DineroNoNegativo"];
      /** @enum {string} */
      metodoAnticipo?: "EFECTIVO" | "TRANSFERENCIA" | "TARJETA" | "OTRO";
      /**
       * Format: date-time
       * @description Máximo 36h atrás y 10m adelante
       */
      fechaVenta?: string;
      items: {
        /** Format: uuid */
        productoId: string;
        cantidad: number;
        precioUnitario?: components["schemas"]["DineroPositivo"];
      }[];
      plan?: components["schemas"]["PlanPago"];
    };
    AbonoEntrada: {
      /** Format: uuid */
      clienteId: string;
      /** Format: uuid */
      ventaId?: string | null;
      monto: components["schemas"]["DineroPositivo"];
      /** @enum {string} */
      metodo?: "EFECTIVO" | "TRANSFERENCIA" | "TARJETA" | "OTRO";
      /**
       * Format: date-time
       * @description Máximo 36h atrás y 10m adelante
       */
      fechaAbono?: string;
      referencia?: string;
      idOperacionMovil?: string;
    };
    ResumenAgendaCobranza: {
      /** @description Clientas distintas */
      cantidad: number;
      /** @description Abonos programados */
      cuotas: number;
      total: number;
    };
    ResumenCobrado: {
      cantidad: number;
      total: number;
    };
    AgendaCobranza: {
      hoy: components["schemas"]["ResumenAgendaCobranza"] & {
        /** Format: date */
        fecha: string;
        items?: unknown[];
      };
      semana: components["schemas"]["ResumenAgendaCobranza"] & {
        /** Format: date */
        inicio: string;
        /** Format: date */
        fin: string;
        dias: (components["schemas"]["ResumenAgendaCobranza"] & {
          /** Format: date */
          fecha?: string;
        })[];
      };
      vencidos: components["schemas"]["ResumenAgendaCobranza"];
      cobrado: {
        hoy: components["schemas"]["ResumenCobrado"];
        semana: components["schemas"]["ResumenCobrado"];
      };
    };
    CategoriaProducto: {
      /** Format: uuid */
      id: string;
      nombre: string;
    };
    CatalogosProducto: {
      marcas: string[];
      categorias: components["schemas"]["CategoriaProducto"][];
    };
    ProductoEntrada: {
      sku: string;
      nombre: string;
      marca: string;
      /** Format: uuid */
      categoriaId: string;
      codigoBarras?: string | null;
      codigoQr?: string | null;
      existenciaInicial?: number;
      existenciaMinima: number;
      precioVenta: components["schemas"]["DineroPositivo"];
      precioCompra: components["schemas"]["DineroNoNegativo"];
      /** @description Imagen base64 procesada y almacenada como archivo WebP; PostgreSQL conserva sólo la ruta. */
      foto?: Record<string, never>;
    };
    OperacionOffline: {
      idOperacion: string;
      /** @enum {string} */
      tipo: "VISITA" | "ABONO" | "VENTA" | "ENTREGA";
      secuencia: number;
      hashAnterior: string;
      /** Format: date-time */
      creadoEn: string;
      hashIntegridad: string;
      datos: Record<string, never>;
    };
    LoteOffline: {
      idLoteCliente: string;
      dispositivoId: string;
      huellaIntegridad: string;
      operaciones: components["schemas"]["OperacionOffline"][];
    };
  };
  responses: {
    /** @description Operación correcta */
    Exito: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    /** @description Página correcta */
    Pagina: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Pagina"];
      };
    };
    /** @description Error estable de aplicación */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    Id: string;
    Pagina: number;
    Limite: number;
    Buscar: string;
    Fecha: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  postAuthIniciarSesion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InicioSesion"];
      };
    };
    responses: {
      200: components["responses"]["Exito"];
      401: components["responses"]["Error"];
      423: components["responses"]["Error"];
      429: components["responses"]["Error"];
    };
  };
  postAuthRenovar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          refreshToken?: string;
        };
      };
    };
    responses: {
      200: components["responses"]["Exito"];
      401: components["responses"]["Error"];
      403: components["responses"]["Error"];
    };
  };
  postAuthCerrarSesion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sesión cerrada */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  getAuthSesion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  postAuthCambiarContrasena: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          contrasenaActual: string;
          nuevaContrasena: string;
        };
      };
    };
    responses: {
      /** @description Contraseña cambiada */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components["responses"]["Error"];
    };
  };
  postAuthMfaIniciar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      403: components["responses"]["Error"];
    };
  };
  postAuthMfaConfirmar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  postAuthMfaDeshabilitar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description MFA deshabilitado */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components["responses"]["Error"];
    };
  };
  getUsuarios: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postUsuarios: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  patchUsuariosId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  postUsuariosIdRestablecerContrasena: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restablecida */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components["responses"]["Error"];
    };
  };
  getClientes: {
    parameters: {
      query?: {
        pagina?: components["parameters"]["Pagina"];
        limite?: components["parameters"]["Limite"];
        buscar?: components["parameters"]["Buscar"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postClientes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClienteEntrada"];
      };
    };
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  getClientesId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      404: components["responses"]["Error"];
    };
  };
  patchClientesId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  patchClientesIdTarjeta: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  patchClientesIdSaldo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  getClientesIdEstadoCuenta: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Estado de cuenta */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  getLocalidades: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postLocalidades: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  patchLocalidadesId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getRutas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postRutas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  patchRutasId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getRutasClientesConSaldo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  postRutasIdVisitas: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getRutasDirectorioCobranza: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getRutasIdClientesExtraordinarios: {
    parameters: {
      query?: {
        buscar?: components["parameters"]["Buscar"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  getRutasIdJornada: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  "getRutasIdHoja.pdf": {
    parameters: {
      query: {
        fecha: components["parameters"]["Fecha"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PDF de la hoja de cobranza */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
      "4XX": components["responses"]["Error"];
    };
  };
  "getRutasIdResultado.pdf": {
    parameters: {
      query: {
        fecha: components["parameters"]["Fecha"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PDF de resultados de cobranza */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
      "4XX": components["responses"]["Error"];
    };
  };
  getRutasIdHistorial: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  getVentas: {
    parameters: {
      query?: {
        pagina?: components["parameters"]["Pagina"];
        limite?: components["parameters"]["Limite"];
        buscar?: components["parameters"]["Buscar"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postVentas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VentaEntrada"];
      };
    };
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  getVentasId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getAbonos: {
    parameters: {
      query?: {
        pagina?: components["parameters"]["Pagina"];
        limite?: components["parameters"]["Limite"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postAbonos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AbonoEntrada"];
      };
    };
    responses: {
      /** @description Reintento idempotente */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      201: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  getAbonosAgenda: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agenda de cuotas y cobros dentro del alcance del usuario */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgendaCobranza"];
        };
      };
      "4XX": components["responses"]["Error"];
    };
  };
  postAbonosRiesgoRecalcular: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  postAbonosIdAnular: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  getInventarioProductos: {
    parameters: {
      query?: {
        pagina?: components["parameters"]["Pagina"];
        limite?: components["parameters"]["Limite"];
        buscar?: components["parameters"]["Buscar"];
        categoriaId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postInventarioProductos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductoEntrada"];
      };
    };
    responses: {
      201: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  getInventarioCatalogosProducto: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Catálogos activos */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogosProducto"];
        };
      };
      "4XX": components["responses"]["Error"];
    };
  };
  postInventarioCategoriasProducto: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          nombre: string;
        };
      };
    };
    responses: {
      200: components["responses"]["Exito"];
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getInventarioProductosCodigoCodigo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        codigo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      404: components["responses"]["Error"];
    };
  };
  deleteInventarioProductosId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Baja aplicada */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  patchInventarioProductosId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getInventarioProductosIdFoto: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JPEG, PNG o WebP */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No modificada */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["Error"];
    };
  };
  postInventarioProductosIdAjuste: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  getInventarioMovimientos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  getCompras: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postCompras: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  getProveedores: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postProveedores: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getProveedoresOpciones: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      403: components["responses"]["Error"];
    };
  };
  patchProveedoresId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getPedidos: {
    parameters: {
      query?: {
        clienteId?: string;
        pagina?: components["parameters"]["Pagina"];
        limite?: components["parameters"]["Limite"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postPedidos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          clienteId: string;
          /** Format: date-time */
          fechaCompromiso?: string;
          notas?: string;
          items: {
            /** Format: uuid */
            productoId: string;
            cantidad: number;
          }[];
        };
      };
    };
    responses: {
      201: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  patchPedidosIdEstado: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  postPedidosIdEntregar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      422: components["responses"]["Error"];
    };
  };
  getDevoluciones: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postDevoluciones: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  getDevolucionesIdEvidencia: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Imagen privada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["Error"];
    };
  };
  getCortesOperadores: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  getCortesPrevisualizar: {
    parameters: {
      query: {
        usuarioOperadorId: string;
        fecha: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getCortes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  postCortes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  getSincronizacionCatalogo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  postSincronizacionDispositivosRegistrar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      409: components["responses"]["Error"];
    };
  };
  getSincronizacionDispositivos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  patchSincronizacionDispositivosIdRevocar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  postSincronizacionDispositivosIdReemplazar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  getSincronizacionRevisiones: {
    parameters: {
      query?: {
        pendientes?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  patchSincronizacionRevisionesIdResolver: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  postSincronizacionLotes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoteOffline"];
      };
    };
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  getReportesResumen: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  "getReportesVentas.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description XLSX */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  "getReportesClientes.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description XLSX */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  "getReportesPedidosPendientes.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PDF */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  getAlertas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      "4XX": components["responses"]["Error"];
    };
  };
  getAuditoria: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Pagina"];
      "4XX": components["responses"]["Error"];
    };
  };
  "getImportacionesPlantilla.xlsx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description XLSX */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      "4XX": components["responses"]["Error"];
    };
  };
  postImportacionesExcel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Exito"];
      409: components["responses"]["Error"];
      422: components["responses"]["Error"];
    };
  };
  getReconciliacion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Exito"];
      403: components["responses"]["Error"];
    };
  };
}
