import { StyleSheet } from "react-native";

import { colores } from "../../../tema";

export const estilosReplica = StyleSheet.create({
  dispositivo: { borderWidth: 1, borderRadius: 20, overflow: "hidden" },
  barraAplicacion: {
    minHeight: 56,
    backgroundColor: colores.azulOscuro,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  marca: { color: "white", fontSize: 16, fontWeight: "900" },
  nombrePantalla: {
    color: "#a6c8ff",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 2,
  },
  insigniaPractica: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,.13)",
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  puntoPractica: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#42be65",
  },
  insigniaTexto: {
    color: "white",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  contenido: { padding: 13, gap: 12 },
  expandir: { flex: 1, minWidth: 0 },
  objetivo: {
    borderWidth: 1,
    borderRadius: 13,
    padding: 11,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  objetivoEtiqueta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  objetivoTexto: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    marginTop: 2,
  },
  titulo: { fontSize: 18, lineHeight: 23, fontWeight: "900", marginTop: 2 },
  filaTitulo: { flexDirection: "row", alignItems: "center", gap: 10 },
  detalle: { fontSize: 12, lineHeight: 17, marginTop: 3 },
  ayuda: { fontSize: 12, lineHeight: 17 },
  tarjetaRuta: {
    minHeight: 82,
    borderWidth: 2,
    borderRadius: 15,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  iconoRuta: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  filaBotones: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  botonMitad: { flexGrow: 1, flexBasis: 130 },
  rejilla: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  tarjetaInicio: {
    flexGrow: 1,
    flexBasis: 130,
    minHeight: 108,
    borderWidth: 1,
    borderRadius: 14,
    padding: 13,
  },
  tarjetaInicioTitulo: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
    marginTop: 10,
  },
  panel: { borderWidth: 1, borderRadius: 14, padding: 13, gap: 11 },
  selector: {
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  dato: { gap: 3 },
  datoEtiqueta: { fontSize: 12, lineHeight: 17, fontWeight: "800" },
  datoValor: { fontSize: 14, lineHeight: 19, fontWeight: "800" },
  retro: {
    borderRadius: 12,
    padding: 11,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  retroTexto: { flex: 1, fontSize: 12, lineHeight: 17, fontWeight: "800" },
});
